// Shared, typed reading of `content/measurements/data/eras.json` for the
// /measurements/ route (and the mirror tests). The JSON is GENERATED by
// `make measurements` (scripts under scripts/measurements-*.py) — never hand-edit it,
// and never re-derive these views from a chapter. Modelled on src/lib/timeline.ts:
// the JSON stays the single source of truth, this module is the thin typed consumer.
//
// The binding shape rule (inc5a D5): the eras are a five-entry LIST, never a hardcoded
// pair or a three-band collapse. Nothing here hardcodes the count or a fixed pair —
// every view maps over `eras`. `group` is a colour/section tag only; it never reduces
// the five rows to their three groups.
import data from '../../content/measurements/data/eras.json';

// ── Raw JSON shapes ───────────────────────────────────────────────────────────
// `metrics` differs per era by construction (each tool measures to a different depth),
// so it stays loosely typed here — tests/measurements.test.ts pins the per-era shapes.
export type EraId = 'copilot' | 'continue' | 'codex' | 'cursor' | 'claude-code';
export type TokenState = 'yes' | 'floor' | 'none';
export type CostState = 'derived' | 'near-zero-local' | 'unknown-server-side' | 'absent';
export type Group = 'vscode-plugin' | 'cursor' | 'claude-code';

export interface Availability {
  tokens: TokenState;
  cost: CostState;
  counts: string;
  skills: 'yes' | 'none';
}

export interface SkillsBlock {
  liveSkillFiles: number;
  commits: number;
  commitsAreFloor: boolean;
  datesAre: string;
  vcStart: string;
  vcEnd: string;
  caveat: string;
  example: { name: string; bucket: string; commits: number; firstCommit: string; snapshotDate: string };
}

export interface Era {
  id: EraId;
  tool: string;
  group: Group;
  availability: Availability;
  configDir: string | null;
  gitCommits: number | null;
  gitStart: string | null;
  gitEnd: string | null;
  logStart: string;
  logEnd: string;
  provenance: { git: string | null; logs: string; skills?: string; configRepo: string };
  metrics: Record<string, any>;
  skills?: SkillsBlock;
}

/** The five eras, in spec order (Copilot → Claude Code). A list, never a pair. */
export const eras = data.eras as unknown as Era[];

/** The stt-faster experimentation corpus — a top-level sibling of the era list. */
export const sttFaster = (data as { sttFaster: Record<string, any> }).sttFaster;

// ── Time axis over the REAL spans ─────────────────────────────────────────────
// Each era's displayed span is the UNION of its git range and its log range — the
// two disagree (that is a shown finding, below), so the axis must cover both. Copilot
// has no git range (gitStart/gitEnd null), so the union folds to the log range alone.
export type Domain<T> = readonly [T, T];

function minDate(...dates: (string | null)[]): string {
  return dates.filter((d): d is string => d !== null).reduce((a, b) => (a < b ? a : b));
}
function maxDate(...dates: (string | null)[]): string {
  return dates.filter((d): d is string => d !== null).reduce((a, b) => (a > b ? a : b));
}

export interface EraSpan {
  id: EraId;
  tool: string;
  group: Group;
  start: string; // union start of git + log
  end: string; // union end of git + log
}

/** Per-era displayed span (git ∪ log), derived — never hardcoded. */
export const eraSpans: EraSpan[] = eras.map((e) => ({
  id: e.id,
  tool: e.tool,
  group: e.group,
  start: minDate(e.gitStart, e.logStart),
  end: maxDate(e.gitEnd, e.logEnd),
}));

// DERIVED from the spans, so a regenerated eras.json widens the axis instead of
// clamping against a stale literal. Exported and pinned by a test that names the data.
export const TIME_DOMAIN: Domain<string> = [
  eraSpans.reduce((min, s) => (s.start < min ? s.start : min), eraSpans[0]!.start),
  eraSpans.reduce((max, s) => (s.end > max ? s.end : max), eraSpans[0]!.end),
];

function days(date: string): number {
  return Date.parse(`${date}T00:00:00Z`) / 86_400_000;
}
function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}

/** Position of an ISO date on the shared time axis, as a fraction in [0, 1]. */
export function dateFraction(date: string, domain: Domain<string> = TIME_DOMAIN): number {
  const [start, end] = domain;
  const span = days(end) - days(start);
  if (span <= 0) return 0;
  return clamp((days(date) - days(start)) / span, 0, 1);
}

// ── Overlap: the structural guard against a false "sequential" claim ───────────
/** Two spans overlap iff each starts on or before the other ends (closed intervals). */
export function overlaps(a: EraSpan, b: EraSpan): boolean {
  return a.start <= b.end && b.start <= a.end;
}

export interface OverlapPair {
  a: EraId;
  b: EraId;
  start: string; // the shared interval
  end: string;
}

/** Every unordered pair of eras whose displayed spans intersect — derived, non-empty. */
export const overlappingPairs: OverlapPair[] = eras.flatMap((_, i) =>
  eraSpans.slice(i + 1).map((b) => ({ a: eraSpans[i]!, b })).filter(({ a, b }) => overlaps(a, b)).map(
    ({ a, b }) => ({
      a: a.id,
      b: b.id,
      start: a.start > b.start ? a.start : b.start,
      end: a.end < b.end ? a.end : b.end,
    }),
  ),
);

/** The overlapping pairs named for the axis's `data-overlap` attribute. */
export const overlapLabel = overlappingPairs.map((p) => `${p.a}∩${p.b}`).join(' ');

// ── Token headline: a FLOOR over the four token-bearing tools (D2 as amended) ──
// Bearing = availability.tokens !== 'none' → continue, codex, cursor, claude-code
// (Copilot logs no token field). The headline sum is `input + cacheCreation + output`
// per tool; `cacheRead` is kept SEPARATE and never enters the headline (D2 cache rule).
// Each era stores its tokens differently, so a per-era adapter pulls the three-class
// sum out of its own shape.
interface TokenSum {
  headline: number; // input + cacheCreation + output
  cacheRead: number; // reuse, shown beside the headline — never inside it
}

function claudeSideSum(side: { input: number; cacheCreation: number; cacheRead: number; output: number }): TokenSum {
  return { headline: side.input + side.cacheCreation + side.output, cacheRead: side.cacheRead };
}

export interface TokenContribution {
  id: EraId;
  tool: string;
  state: TokenState; // 'yes' or 'floor' — the four bearing tools only
  headline: number; // three-class sum used in the primary floor
  cacheRead: number;
  // Claude Code only (D1): main and main+subagent, side by side, BOTH — never one
  // silently. `headline` above equals `sides.mainPlusSubagent.headline`.
  sides?: { main: TokenSum; mainPlusSubagent: TokenSum };
}

function tokenContribution(e: Era): TokenContribution {
  const base = { id: e.id, tool: e.tool, state: e.availability.tokens };
  const m = e.metrics;
  switch (e.id) {
    case 'continue':
      // prompt/generated; no cache classes exist for a local plugin.
      return { ...base, headline: m.tokens.promptTokens + m.tokens.generatedTokens, cacheRead: 0 };
    case 'codex':
      // input_tokens + output_tokens (cached_input / reasoning_output are SUBSETS,
      // already inside those two — adding either double-counts, so cacheRead stays 0).
      return { ...base, headline: m.tokens.input_tokens + m.tokens.output_tokens, cacheRead: 0 };
    case 'cursor':
      return { ...base, headline: m.tokens.input + m.tokens.output, cacheRead: 0 };
    case 'claude-code': {
      const main = claudeSideSum(m.main.tokens);
      const sub = claudeSideSum(m.subagent.tokens);
      const both: TokenSum = {
        headline: main.headline + sub.headline,
        cacheRead: main.cacheRead + sub.cacheRead,
      };
      return { ...base, headline: both.headline, cacheRead: both.cacheRead, sides: { main, mainPlusSubagent: both } };
    }
    default:
      // Copilot and any future non-bearing tool: excluded from the headline entirely.
      return { ...base, headline: 0, cacheRead: 0 };
  }
}

const bearingEras = eras.filter((e) => e.availability.tokens !== 'none');

export const tokenHeadline = {
  qualifier: '≥' as const,
  bearingCount: bearingEras.length, // 4
  totalTools: eras.length, // 5
  label: `≥ tokens · ${bearingEras.length} of ${eras.length} tools`,
  contributions: bearingEras.map(tokenContribution),
  // Two floor totals, because Claude Code contributes BOTH (D1): the primary floor
  // uses main + subagent; `floorMain` uses main only. Neither folds cacheRead in.
  get floor(): number {
    return this.contributions.reduce((sum, c) => sum + c.headline, 0);
  },
  get floorMain(): number {
    return this.contributions.reduce((sum, c) => sum + (c.sides ? c.sides.main.headline : c.headline), 0);
  },
  get cacheRead(): number {
    return this.contributions.reduce((sum, c) => sum + c.cacheRead, 0);
  },
};

// ── Cost: four typed states, each in its own terms (D4), never flattened ───────
export interface CostStateRow {
  id: EraId;
  tool: string;
  state: CostState;
  note: string; // the state phrased in THIS era's terms — not a shared unknown
  usd: number | null; // only `derived` carries a number; nothing is estimated
}

const COST_NOTES: Record<CostState, string> = {
  derived: 'Derived from the transcript logs — real per-model spend.',
  'near-zero-local': 'Local Ollama inference: near-zero marginal money — a finding, not an unknown.',
  'unknown-server-side': 'Priced server-side; no cost field survives locally, and none is estimated here.',
  absent: 'Free tier — the logs bill nothing and carry no cost field.',
};

export const costStates: CostStateRow[] = eras.map((e) => ({
  id: e.id,
  tool: e.tool,
  state: e.availability.cost,
  note: COST_NOTES[e.availability.cost],
  usd: e.availability.cost === 'derived' ? (e.metrics.cost?.totalUSD ?? null) : null,
}));

// ── Cross-check: git range vs log range, the delta SHOWN not reconciled ────────
export interface CrossCheckRow {
  id: EraId;
  tool: string;
  gitStart: string | null;
  gitEnd: string | null;
  logStart: string;
  logEnd: string;
  startDeltaDays: number | null; // log - git, positive = log starts later
  endDeltaDays: number | null;
  disagrees: boolean; // any non-zero delta; false only when git ranges git == log
}

export const crossCheck: CrossCheckRow[] = eras.map((e) => {
  const hasGit = e.gitStart !== null && e.gitEnd !== null;
  const startDeltaDays = hasGit ? days(e.logStart) - days(e.gitStart!) : null;
  const endDeltaDays = hasGit ? days(e.logEnd) - days(e.gitEnd!) : null;
  return {
    id: e.id,
    tool: e.tool,
    gitStart: e.gitStart,
    gitEnd: e.gitEnd,
    logStart: e.logStart,
    logEnd: e.logEnd,
    startDeltaDays,
    endDeltaDays,
    disagrees: hasGit ? startDeltaDays !== 0 || endDeltaDays !== 0 : false,
  };
});

// ── Availability matrix: five named rows; skills empty for eras 0–3 (D5/D6) ────
export interface MatrixRow {
  id: EraId;
  tool: string;
  group: Group;
  tokens: TokenState;
  cost: CostState;
  counts: string;
  skills: SkillsBlock | null; // null renders EMPTY — the emptiness must show, not hide
}

export const availabilityMatrix: MatrixRow[] = eras.map((e) => ({
  id: e.id,
  tool: e.tool,
  group: e.group,
  tokens: e.availability.tokens,
  cost: e.availability.cost,
  counts: e.availability.counts,
  skills: e.skills ?? null,
}));

// ── Caveats: the findings that must never silently drop, as derived data ───────
// Authored here (not in the JSON) because they are the PAGE's rendering obligation.
// The mirror tests assert each string is present; a red demo removes one and reds.
export interface EraCaveats {
  id: EraId;
  tool: string;
  lines: string[];
}

export const caveats: EraCaveats[] = [
  {
    id: 'continue',
    tool: 'Continue (VS Code)',
    lines: [
      'Cost is near-zero-local: local Ollama inference bills near-zero marginal money — a finding, not an unknown.',
    ],
  },
  {
    id: 'codex',
    tool: 'OpenAI Codex plugin',
    lines: [
      'Token figure is a floor: the token_count event only exists from 2025-09-23, so the first weeks log nothing.',
      'history.jsonl is a 3-line stub, not a prompt log — the counts come from the rollout jsonl instead.',
    ],
  },
  {
    id: 'cursor',
    tool: 'Cursor',
    lines: [
      'Token figure is a floor: only <redacted> of <redacted> bubbles carry a non-zero count, all of them assistant turns.',
      'Tokens are a client-side estimate computed by Cursor; nothing here was billed.',
    ],
  },
];

/** Flattened caveat lines for a page-wide presence check. */
export const allCaveatLines: string[] = caveats.flatMap((c) => c.lines);

// ── Skills: a Claude-Code-era-only attribute (D6) ──────────────────────────────
/** The skills block, exposed only for Claude Code (undefined for every other era). */
export const skills: SkillsBlock | undefined = eras.find((e) => e.id === 'claude-code')?.skills;
