// Shared reading of `content/timeline.json` for every consumer on the site:
// the journey index, the home page and the Timeline island. The JSON itself is
// GENERATED by `scripts/timeline-from-git.py` -- never hand-edit it, and never
// re-derive these rows from `content/journey/00-experiments.md`.
import timeline from '../../content/timeline.json';

export interface TimelineRow {
  repo: string;
  first_commit: string;
  last_commit: string;
  commits: number;
  stage: string;
}

/** The generated rows, already sorted by `first_commit` ascending. */
export const rows: TimelineRow[] = timeline as TimelineRow[];

// Mirrors MIN_COMMITS in scripts/timeline-from-git.py: below it a repo is an
// experiment line, not a chapter. The generator writes those lines into
// content/journey/00-experiments.md for GitHub; the site reads the same rows
// straight out of timeline.json rather than parsing that file back.
export const MIN_COMMITS = 5;

/** Repos below `MIN_COMMITS` -- the "also tried" list, oldest first. */
export const experiments: TimelineRow[] = rows
  .filter((row) => row.commits < MIN_COMMITS)
  .sort((a, b) => a.first_commit.localeCompare(b.first_commit));

/** A closed numeric or date range, `[min, max]`. */
export type Domain<T> = readonly [T, T];

// Both domains are DERIVED from the rows rather than hardcoded, so a new repo
// widens the chart instead of clamping against a stale literal. They are
// exported (and pinned by a test) so that drifting data reds an assertion that
// names the data -- the pure scale functions below take a domain argument, so
// their own tests run on a fixed range and can only fail on a maths change.
export const COMMIT_DOMAIN: Domain<number> = [
  Math.min(...rows.map((row) => row.commits)),
  Math.max(...rows.map((row) => row.commits)),
];

export const TIME_DOMAIN: Domain<string> = [
  rows.reduce((min, row) => (row.first_commit < min ? row.first_commit : min), rows[0]!.first_commit),
  rows.reduce((max, row) => (row.last_commit > max ? row.last_commit : max), rows[0]!.last_commit),
];

/** Bar thickness in px at the domain floor and ceiling. */
export const MIN_PX = 4;
export const MAX_PX = 22;

/**
 * Bar thickness for a commit count, on a LOG scale -- counts span 2..4980, so a
 * linear map would flatten every repo but crash-dash into the same hairline.
 */
export function commitThickness(commits: number, domain: Domain<number> = COMMIT_DOMAIN): number {
  const [min, max] = domain;
  if (max <= min) return MIN_PX;
  const fraction = (Math.log10(commits) - Math.log10(min)) / (Math.log10(max) - Math.log10(min));
  return clamp(MIN_PX + fraction * (MAX_PX - MIN_PX), MIN_PX, MAX_PX);
}

/** Position of an ISO date on the time axis, as a fraction in [0, 1]. */
export function dateFraction(date: string, domain: Domain<string> = TIME_DOMAIN): number {
  const [start, end] = domain;
  const span = days(end) - days(start);
  if (span <= 0) return 0;
  return clamp((days(date) - days(start)) / span, 0, 1);
}

function days(date: string): number {
  return Date.parse(`${date}T00:00:00Z`) / 86_400_000;
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}
