// Shared reading of `content/timeline.json` for every consumer on the site:
// the journey index, the home page and the Timeline island. The JSON itself is
// GENERATED by `scripts/timeline-from-git.py` -- never hand-edit it, and never
// re-derive these rows from `content/journey/00-experiments.md`.
import timeline from '../../content/timeline.json';
import config from '../../scripts/timeline-config.json';

export interface TimelineRow {
  repo: string;
  first_commit: string;
  last_commit: string;
  commits: number;
  stage: string;
}

/** The generated rows, already sorted by `first_commit` ascending. */
export const rows: TimelineRow[] = timeline as TimelineRow[];

// Below MIN_COMMITS a repo is an experiment line, not a chapter. The value
// lives in scripts/timeline-config.json, read here AND by the generator
// (scripts/timeline-from-git.py) -- one source, no hand-copied mirror. The
// generator writes the experiment lines into content/journey/00-experiments.md
// for GitHub; the site reads the same rows straight out of timeline.json.
export const MIN_COMMITS: number = config.minCommits;

/**
 * A repo earns a chapter -- and a bar on the chart -- when it cleared
 * `MIN_COMMITS` AND lived past a single day. The second half is the
 * inc-era-labels ruling: a repo whose first and last commit fall on the same
 * date is a spike, not a project. `scripts/timeline-from-git.py::is_chapter`
 * is the same predicate on the generator side, and
 * `tests/timeline-lib.test.ts` pins the two readings equal against the JSON.
 */
export const isChapter = (row: TimelineRow): boolean =>
  row.commits >= MIN_COMMITS && row.last_commit > row.first_commit;

/** The drawn rows: everything the chart and the chapter list carry, oldest first. */
export const chapters: TimelineRow[] = rows.filter(isChapter);

/** Everything else -- the "also tried" list, oldest first. */
export const experiments: TimelineRow[] = rows
  .filter((row) => !isChapter(row))
  .sort((a, b) => a.first_commit.localeCompare(b.first_commit));

/** A closed numeric or date range, `[min, max]`. */
export type Domain<T> = readonly [T, T];

// Both domains are DERIVED from the rows rather than hardcoded, so a new repo
// widens the chart instead of clamping against a stale literal. They are
// exported (and pinned by a test) so that drifting data reds an assertion that
// names the data -- the pure scale functions below take a domain argument, so
// their own tests run on a fixed range and can only fail on a maths change.
// Both are derived from `chapters`, not from every row: an experiment is never
// drawn, so a two-commit spike sitting at the domain floor would give the whole
// scale a bar nothing on the page can be compared against.
export const COMMIT_DOMAIN: Domain<number> = [
  Math.min(...chapters.map((row) => row.commits)),
  Math.max(...chapters.map((row) => row.commits)),
];

export const TIME_DOMAIN: Domain<string> = [
  chapters.reduce(
    (min, row) => (row.first_commit < min ? row.first_commit : min),
    chapters[0]!.first_commit,
  ),
  chapters.reduce(
    (max, row) => (row.last_commit > max ? row.last_commit : max),
    chapters[0]!.last_commit,
  ),
];

/** Bar thickness in px at the domain floor and ceiling. */
export const MIN_PX = 4;
export const MAX_PX = 22;

/**
 * Bar thickness for a commit count, on a LOG scale -- counts span 2..4980, so a
 * linear map would flatten every repo but crash-dash into the same hairline.
 */
export function commitThickness(commits: number, domain: Domain<number> = COMMIT_DOMAIN): number {
  const [min, max] = domain;
  if (max <= min) return MIN_PX;
  const fraction = (Math.log10(commits) - Math.log10(min)) / (Math.log10(max) - Math.log10(min));
  return clamp(MIN_PX + fraction * (MAX_PX - MIN_PX), MIN_PX, MAX_PX);
}

/** Position of an ISO date on the time axis, as a fraction in [0, 1]. */
export function dateFraction(date: string, domain: Domain<string> = TIME_DOMAIN): number {
  const [start, end] = domain;
  const span = days(end) - days(start);
  if (span <= 0) return 0;
  return clamp((days(date) - days(start)) / span, 0, 1);
}

function days(date: string): number {
  return Date.parse(`${date}T00:00:00Z`) / 86_400_000;
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}
