import { createHash } from 'node:crypto';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

import { BANNED } from '../src/lib/content-rules';

// The content gate. Three assertions over the authored markdown, each one the
// executable form of a line in `.claude/rules/content-writing.md`:
//   (a) `artifact: present` <=> a non-empty `## Artifact` body   (evidence rule)
//   (b) every chapter carries `## What didn't work`               (anti-hype rule)
//   (c) no content file uses the banned vocabulary                (anti-hype rule)
// Plus one prose-vs-source test: the rule file's banned-vocabulary bullet is
// compared to `src/lib/content-rules.ts`, so a divergence reds instead of
// rotting quietly.

const CONTENT = 'content';
const JOURNEY = join(CONTENT, 'journey');

// Neither file is a chapter: `00-experiments.md` is the one-line-per-repo list
// and `README.md` is generated by scripts/timeline-from-git.py. Both are
// excluded from the Astro journey collection for the same reason (no
// frontmatter), so (a) and (b) cannot apply to them.
const NOT_A_CHAPTER = new Set(['00-experiments.md', 'README.md']);


/** Every `.md` under content/, recursively, minus the generated index. */
function contentFiles(dir = CONTENT): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return contentFiles(path);
    if (!entry.name.endsWith('.md')) return [];
    if (path === join(JOURNEY, 'README.md')) return [];
    return [path];
  });
}

/** The 13 journey chapters, by path. */
function chapters(): string[] {
  return readdirSync(JOURNEY)
    .filter((name) => name.endsWith('.md') && !NOT_A_CHAPTER.has(name))
    .sort()
    .map((name) => join(JOURNEY, name));
}

const read = (path: string) => readFileSync(path, 'utf8');

/** The value of a single frontmatter key, or undefined. */
function frontmatter(body: string, key: string): string | undefined {
  const block = body.match(/^---\n([\s\S]*?)\n---\n/);
  if (!block) return undefined;
  const line = block[1].match(new RegExp(`^${key}:\\s*(.*)$`, 'm'));
  return line?.[1].trim();
}

/** The body under `## <heading>`, up to the next `## ` or EOF. */
function section(body: string, heading: string): string | undefined {
  const start = body.match(new RegExp(`^## ${heading}\\s*$`, 'm'));
  if (start?.index === undefined) return undefined;
  const after = body.slice(start.index + start[0].length);
  const next = after.search(/^## /m);
  return (next === -1 ? after : after.slice(0, next)).trim();
}

/**
 * A whole-word match for `word`, safe for entries that begin or end with a
 * non-word character. `\b` cannot express a boundary next to `+` or `.`, so a
 * future banned entry like `C++` would compile to a regex that never matches —
 * unenforced, and silent about it. Explicit lookarounds have no such hole.
 */
function bounded(word: string): string {
  const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return `(?<![A-Za-z0-9])${escaped}(?![A-Za-z0-9])`;
}

const CONTENT_FILES = contentFiles();
const CHAPTERS = chapters();

describe('premise guards', () => {
  // A vacuous suite passes forever. Each of the three assertions below iterates
  // over a set that could be empty by accident (a moved directory, an emptied
  // list); these fail loudly when it is.
  it('has a non-empty banned-vocabulary list', () => {
    expect(BANNED.length).toBeGreaterThan(0);
  });

  it('found the journey chapters', () => {
    expect(CHAPTERS.length).toBeGreaterThan(0);
  });

  it('found the content files to sweep', () => {
    expect(CONTENT_FILES.length).toBeGreaterThan(0);
  });
});

describe('evidence rule', () => {
  // (a) The frontmatter enum and the prose must agree. `present` claims an
  // artifact block, so the section body must carry one; `pending` is the stub
  // state timeline-from-git.py emits — heading, nothing under it. Checking only
  // that the heading exists would be vacuous (every chapter has one).
  it.each(CHAPTERS)('%s: artifact frontmatter matches the Artifact body', (path) => {
    const body = read(path);
    const declared = frontmatter(body, 'artifact');
    // The enum is also the Zod schema's, and `astro build` runs before vitest in
    // `make check` — but assert it here too so `make test` stands on its own and
    // a typo cannot fall through to the `pending` branch below.
    expect([`present`, `pending`], `${path}: \`artifact: ${declared}\``).toContain(declared);

    const artifact = section(body, 'Artifact');
    expect(artifact, `${path}: no \`## Artifact\` heading`).toBeDefined();

    if (declared === 'present') {
      expect(artifact, `${path}: \`artifact: present\` but the section is empty`).not.toBe('');
    } else {
      expect(artifact, `${path}: \`artifact: ${declared}\` but the section has a body`).toBe('');
    }
  });
});

// The context ledger (2026-09-08 reframe, plan §9 item 1). Five enumerated
// fields per chapter; `astro build` already rejects a value outside its Zod
// enum, so what is left to assert is the tie between a ledger CLAIM and the
// evidence the chapter shows for it.
//
// inc5g reinstates the STRICT reading, which decision §5 had deliberately
// rejected so the stub chapters could get their ledger before their prose. That
// concession expired the day the `/journey/` comparison table shipped: the table
// is the reframe's proof, and 7 of its 13 rows were drawing five enumerated
// claims from 53-word stubs with an empty `## Artifact`. The seven stubs gave up
// their ledger keys instead (inc5g); a chapter earns them back by writing the
// artifact first, which is the drafting order this gate now enforces.
//
// The chain is three links, and each one is a separate way to fail:
//   1. a ledger key is filled            -- the chapter makes a claim
//   2. the `## Artifact` body is non-empty -- it offers evidence for it
//   3. that body quotes or fences        -- the evidence is SHOWN, not described
// Link 3 is what stops a paragraph *about* an artifact from passing as one. All
// six ledger-carrying chapters satisfy it today, so it costs nothing on arrival
// and binds every chapter added after.
const LEDGER_KEYS = ['could_see', 'retrieved', 'versioned', 'verified_by', 'cost_to_look'];

/** A fenced block or a blockquote: the artifact itself, rather than prose about it. */
const SHOWS_ARTIFACT = /^(?:```|>)/m;

describe('context ledger', () => {
  it.each(CHAPTERS)('%s: a chapter carrying a ledger shows its artifact', (path) => {
    const body = read(path);
    const filled = LEDGER_KEYS.filter((key) => frontmatter(body, key) !== undefined);
    if (filled.length === 0) return;

    const artifact = section(body, 'Artifact');
    expect(
      artifact,
      `${path}: ledger keys ${filled.join(', ')} claimed, but the Artifact section is empty`,
    ).not.toBe('');

    expect(
      artifact,
      `${path}: ledger keys ${filled.join(', ')} claimed, but the Artifact section only ` +
        `describes the evidence -- it must quote or fence it`,
    ).toMatch(SHOWS_ARTIFACT);
  });

  // Vacuity anchor. Every `filled.length === 0` chapter returns before asserting
  // anything, so a frontmatter parser that silently stopped matching would drain
  // the population and leave the block above green over a row of no-ops. Anchor
  // on both sides of the count the drafting order moves: a collapse to zero is a
  // broken parser, and a ledger on every repo-backed chapter means the stubs got
  // theirs back without the artifact that is supposed to buy it.
  //
  // The upper bound is a SUBSET relation, deliberately not `carrying <
  // repoBacked`. A strict count inequality anchors on the population the work
  // drains -- the anti-pattern `testing-project.md` names -- so it would red the
  // day all 13 chapters legitimately carry a ledger WITH the artifact that buys
  // it, conflating a finished corpus with a stub sneaking its keys back. The
  // stub case is already link 2's job, per-chapter and with a better message.
  // What is left for the anchor is the containment link 2 cannot see: a ledger
  // on a chapter that has no repo to read one off.
  it('the ledger population is a subset of the repo-backed chapters', () => {
    const carries = (path: string) =>
      LEDGER_KEYS.some((key) => frontmatter(read(path), key) !== undefined);
    const carrying = CHAPTERS.filter(carries);
    const strays = CHAPTERS.filter(
      (path) => carries(path) && frontmatter(read(path), 'repo') === undefined,
    );

    expect(carrying.length, 'no chapter carries a ledger -- the parser is broken').toBeGreaterThan(0);
    expect(
      strays,
      'a chapter with no repo carries a ledger -- there is nothing to have read it off',
    ).toEqual([]);
  });
});

describe('anti-hype rule', () => {
  // (b) Failures get equal billing: the heading is the structural guarantee.
  it.each(CHAPTERS)("%s: has a `## What didn't work` section", (path) => {
    expect(section(read(path), "What didn't work")).toBeDefined();
  });

  // (c) Word-boundary, case-insensitive, across every authored content file --
  // not just the chapters -- because the rule's own `paths:` is content/**/*.md.
  it.each(CONTENT_FILES)('%s: uses no banned vocabulary', (path) => {
    const body = read(path);
    const hits = BANNED.filter((word) => new RegExp(bounded(word), 'i').test(body));
    expect(hits, `${path}: banned vocabulary`).toEqual([]);
  });
});

describe('rule prose vs its machine half', () => {
  // `BANNED` has ONE machine source (`src/lib/content-rules.ts`); the rule file
  // restates it as prose for authors. Parse the rule's bullet and compare the
  // two sets, so adding a word in one place and not the other reds here rather
  // than silently going unenforced.
  it('banned list matches `content-writing.md` §Anti-hype', () => {
    const rule = read(join('.claude', 'rules', 'content-writing.md'));
    const bullet = rule.match(/^- \*\*Banned vocabulary\*\*[^\n]*\n(?:[ \t]+[^\n]*\n)*/m);
    expect(bullet, 'could not find the `Banned vocabulary` bullet').not.toBeNull();

    const fromRule = [...bullet![0].matchAll(/`([^`]+)`/g)].map((m) => m[1]);
    expect(new Set(fromRule)).toEqual(new Set(BANNED));
  });

  // `content/timeline.json` is generated, so these assert the GENERATOR's two
  // honesty rules rather than hand-authored prose.
  //
  // (1) End-dates exclude AI-config-only commits. A `chore(claude):` deny-list
  //     sweep touched 13 repos on 2026-09-06; counting it made every one of them
  //     claim activity that day. `dewpoint`'s pinned date is the discriminating
  //     case: it moves 14 months if the exclusion pathspec is dropped.
  // (2) `dewpoint-app` (the Python original) and `dewpoint-ts` (the Node port
  //     made to deploy on Vercel) are ONE project, so they collapse into a
  //     single `dewpoint` row via the generator's REPO_GROUPS map.
  //
  // The pinned dates are data assertions naming a specific value on purpose: if
  // one of these repos is legitimately reactivated, this test reds and the line
  // has to be re-pinned. That is real work being flagged, not a false alarm.
  describe('timeline.json honesty', () => {
    const rows: Array<{
      repo: string;
      first_commit: string;
      last_commit: string;
      commits: number;
      stage: string;
    }> = JSON.parse(read(join(CONTENT, 'timeline.json')));

    // Vacuity anchors: a parser that silently yields [] or a truncated array
    // would let every assertion below pass by looping over nothing.
    it('parses to the full 14-row corpus', () => {
      expect(Array.isArray(rows)).toBe(true);
      expect(rows).toHaveLength(14);
    });

    it('dates the dewpoint row past the AI-config sweep, not on it', () => {
      const dewpoint = rows.find((r) => r.repo === 'dewpoint');
      expect(dewpoint, 'no dewpoint row in timeline.json').toBeDefined();
      // Drop `:(exclude).claude/**` & friends from the generator and this
      // becomes 2026-09-06 -- the sweep date.
      expect(dewpoint!.last_commit).toBe('2026-06-25');
      expect(dewpoint!.first_commit).toBe('2025-07-15');
    });

    it('merges the two dewpoint repos into one row', () => {
      expect(rows.filter((r) => r.repo.startsWith('dewpoint'))).toHaveLength(1);
      for (const gone of ['dewpoint-app', 'dewpoint-ts']) {
        expect(rows.some((r) => r.repo === gone), `${gone} still a row`).toBe(false);
      }
      // 4 commits in the Python original + 102 in the TS port.
      expect(rows.find((r) => r.repo === 'dewpoint')!.commits).toBe(106);
    });

    // The 2026-09-06 `chore(claude):` sweep touched AI-config in 13 repos; the
    // AI_CONFIG_PATHS exclusions mean only the two doing real work that day may be
    // dated on or after it. Pinned as `>=`, not `=== SWEEP_DAY`: both repos have
    // since committed again, and a pin on the day itself goes vacuously green the
    // moment they move on — which is also how it would look if the exclusions broke.
    it('leaves only the genuinely-active repos dated on or after the sweep day', () => {
      const SWEEP_DAY = '2026-09-06';
      const since = rows.filter((r) => r.last_commit >= SWEEP_DAY).map((r) => r.repo);
      expect(since.sort()).toEqual(['crash-dash', 'dotfiles']);
    });

    it('never ends a repo before it started, or in the future', () => {
      // Read today rather than pinning it: a literal end-date bound reds every time
      // an upstream repo commits, which is drift in the clock, not in the data.
      const today = new Date().toISOString().slice(0, 10);
      for (const r of rows) {
        expect(r.first_commit <= r.last_commit, `${r.repo} ends before it starts`).toBe(true);
        expect(r.last_commit <= today, `${r.repo} ends in the future`).toBe(true);
      }
    });
  });
});

// (d) Provenance: every case-study artifact names the relative path or commit it
// was rewritten from. This is the executable form of the `content/case-study/
// crash-dash/**` admission row ("each with its origin path and date"). It lives
// here rather than in the Zod schema because `index.md` is the landing body, not
// an artifact, and carries no origin -- an always-required schema key would red
// on it. The population assertion is not decoration: without it a rename of the
// directory would empty ARTIFACTS and the guard would pass over nothing.
const CASE_STUDY = join(CONTENT, 'case-study', 'crash-dash');

// The landing body, excluded by exact path rather than by filename: a nested
// `<sub>/index.md` would still be a real artifact with its own route, and an
// `endsWith('index.md')` test would drop it from the check while the route
// shipped it.
const LANDING = join(CASE_STUDY, 'index.md');
const ARTIFACTS = contentFiles(CASE_STUDY).filter((path) => path !== LANDING);

// The admission row says "each with its origin path AND date", so both halves
// are asserted -- an `origin`-only guard leaves a missing `date` green in every
// gate (Zod has it optional so index.md can omit it).
describe('case-study provenance', () => {
  it('there are artifacts to check', () => {
    expect(ARTIFACTS.length, `no artifacts found under ${CASE_STUDY}`).toBeGreaterThan(0);
  });

  it.each(ARTIFACTS)('%s: carries `origin` and `date` frontmatter', (path) => {
    const body = read(path);

    const origin = frontmatter(body, 'origin');
    expect(origin, `${path}: no \`origin:\` in frontmatter`).toBeDefined();
    expect(origin, `${path}: empty \`origin:\``).not.toBe('');

    const date = frontmatter(body, 'date');
    expect(date, `${path}: no \`date:\` in frontmatter`).toBeDefined();
    expect(date, `${path}: \`date:\` is not an ISO day`).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });
});

// The artifacts collection stopped being "reusable prompts" in inc5f: a prompt
// is one of five kinds of context artifact, and the page only makes that claim
// if all five are actually on it. These four assertions are the executable form
// of that claim — the kind enum is parsed back out of `content.config.ts` so
// adding a sixth kind there without an example here reds instead of rotting.
const ARTIFACT_DIR = join(CONTENT, 'artifacts');
const CONTEXT_ARTIFACTS = contentFiles(ARTIFACT_DIR);

/** The `kind` enum as declared in the collection schema, not a hand-copy. */
function artifactKinds(): string[] {
  const config = read(join('src', 'content.config.ts'));
  const decl = config.match(/^export const ARTIFACT_KINDS = \[([^\]]*)\]/m);
  expect(decl, 'no ARTIFACT_KINDS in src/content.config.ts').not.toBeNull();
  return [...decl![1].matchAll(/'([^']+)'/g)].map((m) => m[1]);
}

describe('context artifacts', () => {
  const KINDS = artifactKinds();

  it('there are artifacts to check, and five kinds to check them against', () => {
    expect(CONTEXT_ARTIFACTS.length, `no artifacts found under ${ARTIFACT_DIR}`).toBeGreaterThan(0);
    expect(KINDS.length, 'ARTIFACT_KINDS parsed empty').toBe(5);
  });

  it.each(CONTEXT_ARTIFACTS)('%s: declares a `kind` in the enum', (path) => {
    const kind = frontmatter(read(path), 'kind');
    expect(kind, `${path}: no \`kind:\` in frontmatter`).toBeDefined();
    expect(KINDS, `${path}: \`kind: ${kind}\` is not in ARTIFACT_KINDS`).toContain(kind);
  });

  // The reframe's whole claim. A page naming five kinds while shipping four is
  // the site contradicting itself, and nothing else in the gate would catch it.
  it('every kind has at least one example on the page', () => {
    const present = new Set(CONTEXT_ARTIFACTS.map((path) => frontmatter(read(path), 'kind')));
    expect([...present].sort()).toEqual([...KINDS].sort());
  });

  // Two provenance stories share one page (this repo vs. private/per-machine
  // trees), so every entry has to say which tree it came from and whether the
  // reader can verify it. Frontmatter `source:` is a label; this section is the
  // sentence that admits when there is no public address.
  it.each(CONTEXT_ARTIFACTS)('%s: carries a `## Where it came from` body', (path) => {
    const where = section(read(path), 'Where it came from');
    expect(where, `${path}: no \`## Where it came from\` section`).toBeDefined();
    expect(where!.length, `${path}: empty \`## Where it came from\``).toBeGreaterThan(0);
  });
});


// inc7b — the atom corpus. `astro build` already gates each atom's own schema,
// but it cannot see two things: that a `topic:` names a topic file that exists
// (Zod validates a string, not a reference), and that the facet vocabularies the
// pages and a future deck query against are still the ones declared. Both are
// asserted here, over the source text — vitest has no Astro resolution, so the
// consts are regex-parsed out of the config exactly as ARTIFACT_KINDS is.
const ATOM_DIR = join(CONTENT, 'atoms');
const TOPIC_DIR = join(CONTENT, 'topics');
const ATOMS = contentFiles(ATOM_DIR);

/** A `const` array as DECLARED in the collection schema, not a hand-copy. */
function configEnum(name: string): string[] {
  const config = read(join('src', 'content.config.ts'));
  const decl = config.match(new RegExp(`^export const ${name} = \\[([^\\]]*)\\]`, 'm'));
  expect(decl, `no ${name} in src/content.config.ts`).not.toBeNull();
  return [...decl![1].matchAll(/'([^']+)'/g)].map((m) => m[1]);
}

describe('atom corpus', () => {
  const topicSlugs = new Set(
    readdirSync(TOPIC_DIR)
      .filter((name) => name.endsWith('.md'))
      .map((name) => name.replace(/\.md$/, '')),
  );

  const chapterSlugs = new Set(
    readdirSync(JOURNEY)
      .filter((name) => name.endsWith('.md'))
      .map((name) => name.replace(/\.md$/, '')),
  );

  it('there are atoms, topics and chapters to check', () => {
    expect(ATOMS.length, `no atoms found under ${ATOM_DIR}`).toBeGreaterThan(0);
    expect(topicSlugs.size, `no topics found under ${TOPIC_DIR}`).toBeGreaterThan(0);
    expect(chapterSlugs.size, `no chapters found under ${JOURNEY}`).toBeGreaterThan(0);
  });

  // Referential integrity. This is the whole reason topics are files rather than
  // a free-text tag: a typo'd `topic:` is a broken link on the site and a dead
  // group in the corpus, and nothing else in the gate can see it.
  // Same shape, same reason: `source_chapter` is Stage 4's transclusion key, and
  // Zod validates a string, not a reference. A typo'd or renamed chapter makes an
  // atom transclude onto NOTHING while `astro build` stays green -- the atom still
  // renders at its own route, so nothing else in the gate can see the orphan. The
  // target is the chapter FILE, not the journey collection: `00-experiments` is
  // excluded from the collection on purpose (Stage 4 ruling 2), so an atom mined
  // for it legitimately transcludes nowhere and must still resolve here.
  it.each(ATOMS)('%s: `source_chapter` resolves to a chapter file', (path) => {
    const chapter = frontmatter(read(path), 'source_chapter');
    expect(chapter, `${path}: no \`source_chapter:\` in frontmatter`).toBeDefined();
    expect(
      [...chapterSlugs],
      `${path}: \`source_chapter: ${chapter}\` has no ${join(JOURNEY, `${chapter}.md`)}`,
    ).toContain(chapter);
  });

  it.each(ATOMS)('%s: `topic` resolves to a topic file', (path) => {
    const topic = frontmatter(read(path), 'topic');
    expect(topic, `${path}: no \`topic:\` in frontmatter`).toBeDefined();
    expect(
      [...topicSlugs],
      `${path}: \`topic: ${topic}\` has no ${join(TOPIC_DIR, `${topic}.md`)}`,
    ).toContain(topic);
  });

  // Mirror-totality pins. RUNG_META's precedent: a Record declared total over an
  // enum does not gate a ship, because `make check` runs `astro build`, never
  // `astro check`. These name the members instead, so dropping one reds here.
  it('the six rungs are the ladder the atoms are sorted by', () => {
    expect(configEnum('RUNGS')).toEqual([
      'asking',
      'suggesting',
      'delegating',
      'planning',
      'configuring',
      'governing',
    ]);
  });

  it('the three levels are what an atom does to a listener', () => {
    expect(configEnum('LEVELS')).toEqual(['orient', 'show', 'govern']);
  });

  it('the four evidence kinds are what a shown line can be', () => {
    expect(configEnum('EVIDENCE_KINDS')).toEqual(['defect', 'number', 'artifact', 'transcript']);
  });

  it('the four audiences are the cuts one corpus emits', () => {
    expect(configEnum('AUDIENCES')).toEqual(['university', 'rnd-engineers', 'meetup', 'linkedin']);
  });

  // Fidelity rule: paraphrase everywhere, exactly one verbatim line per atom, and
  // that line carries its date. A second quote block is the leak surface widening
  // one idea at a time, which is what the one-quote ceiling exists to hold.
  it.each(ATOMS)('%s: `## Evidence` carries exactly one dated quote', (path) => {
    const evidence = section(read(path), 'Evidence');
    expect(evidence, `${path}: no \`## Evidence\` section`).toBeDefined();
    const quotes = evidence!.split(/\n(?!>)/).filter((block) => block.trimStart().startsWith('>'));
    expect(quotes.length, `${path}: expected exactly one blockquote in \`## Evidence\``).toBe(1);
    expect(quotes[0], `${path}: the quoted line carries no bracketed date`).toMatch(
      /\[\d{4}-\d{2}(-\d{2})?(\.\.\d{4}-\d{2}(-\d{2})?)?\]/,
    );
  });
});


// inc7b Stage 2 -- the sidecar corpus. Three guards, and what each one exists
// for is recorded in `docs/plans/2026-09-09-inc7-mine-spec.md` §Stage 2 rulings.
const SIDECAR_DIR = join(CONTENT, 'sidecars');
const SIDECARS = contentFiles(SIDECAR_DIR);

describe('sidecar corpus', () => {
  const topicSlugs = new Set(
    readdirSync(TOPIC_DIR)
      .filter((name) => name.endsWith('.md'))
      .map((name) => name.replace(/\.md$/, '')),
  );

  it('there are sidecars to check', () => {
    expect(SIDECARS.length, `no sidecars found under ${SIDECAR_DIR}`).toBeGreaterThan(0);
  });

  // (a) Totality, in BOTH directions. A literal `length === 8` cannot see a
  // ninth directory, which is this stage's own stated falsifier -- so the enum
  // is compared as a SET against the directory listing instead. The consequence
  // is deliberate: every declared type owes a directory on disk, empty or not.
  it('the eight sidecar types are exactly the directories on disk', () => {
    const declared = configEnum('SIDECAR_TYPES');
    const onDisk = readdirSync(SIDECAR_DIR, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name);
    expect(declared.length, 'SIDECAR_TYPES is not eight members').toBe(8);
    expect([...declared].sort(), 'SIDECAR_TYPES and content/sidecars/ have diverged').toEqual(
      [...onDisk].sort(),
    );
  });

  // (b) The fidelity guard, and the reason the schema has no quote field: the
  // public tier DESCRIBES what a source showed. A blockquote is the shape
  // pasted transcript material arrives in, so blockquote lines are the thing
  // rejected -- not every `"..."` span, which false-positives on honest prose
  // quoting (the existing atoms quote a constraint inline and are right to).
  // Accepted, known miss: a quote pasted with no `>` prefix passes this gate.
  // That is a review concern. Do not widen the regex to close it.
  it.each(SIDECARS)('%s: carries no blockquote line', (path) => {
    const lines = read(path).split('\n');
    let fenced = false;
    const quoted: number[] = [];
    lines.forEach((line, i) => {
      if (/^\s*(```|~~~)/.test(line)) fenced = !fenced;
      else if (!fenced && /^\s*>/.test(line)) quoted.push(i + 1);
    });
    expect(quoted, `${path}: blockquote line(s) at ${quoted.join(', ')}`).toEqual([]);
  });

  // (c) Referential integrity, same argument as the atoms': Zod validates that
  // `topic` is a string, never that it names a file.
  it.each(SIDECARS)('%s: `topic` resolves to a topic file', (path) => {
    const topic = frontmatter(read(path), 'topic');
    expect(topic, `${path}: no \`topic:\` in frontmatter`).toBeDefined();
    expect(
      [...topicSlugs],
      `${path}: \`topic: ${topic}\` has no ${join(TOPIC_DIR, `${topic}.md`)}`,
    ).toContain(topic);
  });
});


// The `root page links every top-level route` guard used to live here. inc8
// moved it to `tests/nav.test.ts`: three doors means a route is reachable via
// the root page OR one of the three door indexes, so the assertion could not
// stay pinned to src/pages/index.astro alone.


// inc5c Stage 3a -- the corpus leak class. The ChatGPT exports under sources/
// are gitignored, but their contents reach content/ by hand, and three kinds of
// string must never make that trip: a live thread URL (a `chatgpt.com/c/<uuid>`
// address, plus the `/g/g-p-<id>/` segment that project-folder threads carry),
// a machine or account fingerprint, and a credential shape.
//
// Kept deliberately OUT of `BANNED` (src/lib/content-rules.ts). That list is checked against
// `.claude/rules/content-writing.md` §Anti-hype by the drift guard, so folding
// these in would (a) couple a leak guard to a vocabulary rule and (b) publish
// each pattern in the same breath as `10x` and `magic`. Separate assertion,
// separate failure message.
//
// The literals below (`DESKTOP-26A9125`, the `/home/kristjans` path, the GCP
// project id) are already in this public repo -- `docs/sources-chatgpt-
// conversations2.md` §Sanitisation names all three as the fingerprints it found
// -- so restating them here discloses nothing new. Every other sample is
// fabricated.
//
// The 32 GB VRAM row is a wider bar than "fingerprint": the user ruled that box
// employer-side hardware, so publishing a second ceiling with no personal-
// hardware explanation is itself the disclosure. The 8 GB home ceiling is
// published and stays -- these patterns must not touch it.
const LEAKS: { name: string; pattern: RegExp; sample: string }[] = [
  {
    name: 'live ChatGPT thread URL',
    pattern: /chatgpt\.com\/c\/[0-9a-f]{8}/i,
    sample: 'https://chatgpt.com/c/0badc0de-1111-2222-3333-444455556666',
  },
  {
    name: 'ChatGPT project id',
    pattern: /\/g\/g-p-[0-9a-z]{8}/i,
    sample: 'https://chatgpt.com/g/g-p-0badc0de1111/project',
  },
  {
    name: 'Windows hostname',
    pattern: /DESKTOP-[0-9A-Z]{7}\b/,
    sample: 'DESKTOP-26A9125',
  },
  {
    name: 'WSL home path',
    pattern: /\/home\/kristjans(\/|\b)/i,
    sample: '/home/kristjans/projects/ai-coding-journey',
  },
  {
    name: 'Windows user path',
    pattern: /C:\\Users\\Kristjan/i,
    sample: 'C:\\Users\\Kristjan\\Downloads',
  },
  {
    name: 'GCP project id',
    pattern: /speech2text-\d{6}/i,
    sample: 'speech2text-218910',
  },
  {
    name: 'Hugging Face token',
    pattern: /\bhf_[A-Za-z0-9]{16,}/,
    sample: 'hf_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  },
  {
    name: 'OpenAI-style key',
    pattern: /\bsk-[A-Za-z0-9]{20,}/,
    sample: 'sk-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  },
  {
    name: 'GitHub token',
    pattern: /\bghp_[A-Za-z0-9]{20,}/,
    sample: 'ghp_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  },
  {
    name: 'AWS access key id',
    pattern: /\bAKIA[0-9A-Z]{16}\b/,
    sample: 'AKIAAAAAAAAAAAAAAAAA',
  },
  {
    name: 'office-server VRAM ceiling',
    pattern: /\b32\s*GB\b[^.\n]{0,40}\bVRAM\b/i,
    sample: 'the 32 GB VRAM box',
  },
  {
    name: 'office-server VRAM ceiling (reversed)',
    pattern: /\bVRAM\b[^.\n]{0,40}\b32\s*GB\b/i,
    sample: 'VRAM ceiling of 32 GB',
  },
];

describe('corpus leak class', () => {
  // Premise guard. A leak pattern that cannot match anything passes over every
  // content file forever and reads as proof. Each entry carries a sample of the
  // exact shape it exists to catch; a pattern that stops matching its own sample
  // reds HERE, loudly, instead of going quietly unenforced.
  it.each(LEAKS)('$name: the pattern matches its own sample', ({ pattern, sample }) => {
    expect(pattern.test(sample)).toBe(true);
  });

  // ...and the published 8 GB home ceiling must survive both VRAM patterns --
  // a guard that reds on the figure the journey is built around is unshippable.
  it('the published 8 GB home ceiling is not a leak', () => {
    const published = 'The 8 GB VRAM ceiling capped the model shortlist; VRAM was 8 GB.';
    const hits = LEAKS.filter((leak) => leak.pattern.test(published)).map((leak) => leak.name);
    expect(hits).toEqual([]);
  });

  it.each(CONTENT_FILES)('%s: leaks nothing from the corpus', (path) => {
    const body = read(path);
    const hits = LEAKS.filter((leak) => leak.pattern.test(body)).map((leak) => leak.name);
    expect(hits, `${path}: corpus leak`).toEqual([]);
  });
});

// --- Protected terms -------------------------------------------------------
//
// Names that must never appear in `content/`: they resolve the journey to a
// specific employer and specific colleagues. The words are NOT in this repo --
// only the `sha256` of each, taken after the normalisation below.
//
// This is an ACCIDENTAL-INCLUSION check, not a secrecy mechanism. The digests
// are unsalted sha256 of short, low-entropy strings and the normaliser is
// public in this same file, so anyone with a wordlist can confirm a guess. A
// salt would break the mirror -- the producer and consumer sides must agree --
// so the hole is accepted, not closed. The guarantee therefore extends beyond
// `content/`: **never name a protected term in a commit message, a plan doc, a
// test name or a failure string either.** The digest set is the only place a
// term is allowed to appear, and it appears there as a digest.
//
// Kept separate from `BANNED` (mirrored against `.claude/rules/content-
// writing.md` by the drift guard) and from `LEAKS` (regex shapes, samples in
// the clear). A term here has no publishable sample, so this block gets its own
// premise guard built from a fabricated canary instead.
//
// Normalisation, applied identically to a supplied term and to every content
// n-gram -- the two sides are a mirror, and `the normaliser collapses
// inflections` below is the test that keeps them one:
//   strip diacritics (NFD) -> lowercase -> hyphens to spaces -> `[a-z0-9]+`
//   tokens -> join with one space -> strip a trailing `es` or `s` -> sha256
// so a plural, a possessive, a hyphenated spelling, or an accent dropped from a
// name reds on the same digest. The accent fold is load-bearing, not cosmetic:
// without it a `[a-z0-9]+` split would tear a name like `Jarnvarr` in half at
// the accented letter and hash two fragments that match nothing. (That example
// is fabricated, per the block header: no protected term appears here.)
const PROTECTED_SHA256 = new Set([
  '7036c80e90945cfeb26b20592541d830d83c82f9546eeacbb97a0d48988ed2d4',
  'ec4f2dbb3b140095550c9afbbb69b5d6fd9e814b9da82fad0b34e9fcbe56f1cb',
  '6976fb4b3e420a41e2b45f781beddbde2abb4aecf07bf87d0e73e70a63e22a8f',
  '4d5e87c342601bae11c1fd06bfd92277f9b67c22ebcf7e6bf480e682bcf29c07',
  '5d77db2a2906aed32e92acd7c2fa458c9e2185c836146259418733795ca83de8',
  'bb37067afeb4ee16d668eef073ca6eea4f3b4a1fc6c68e3c0b1fd01a5fb7f5ad',
  '0d2c690e7dd5f94780383e9dfa1f4def044319104ad16ab15e45eeb2a8dfc81b',
  '020df7a901fc42f7543c6bf63dd9874a3aa390a33bf6d8570ff8dc078ebf94d9',
]);

/**
 * The n-gram width the scan emits. A stored term LONGER than this can never be
 * produced on the consumer side, so it would pass over every content file
 * forever and read as proof -- and nothing can assert otherwise, because the
 * terms are not in this repo to be counted. Adding a digest for a term of more
 * than this many tokens REQUIRES bumping this constant in the same edit; the
 * cost is one extra gram per token per position, nothing more.
 */
const PROTECTED_MAX_TOKENS = 3;

const normalise = (gram: string) => gram.replace(/(es|s)$/, '');

/** Diacritics stripped, lowercased, hyphens opened out -- shared by both sides. */
const fold = (value: string) =>
  value.normalize('NFD').replace(/\p{Diacritic}/gu, '').toLowerCase().replace(/-/g, ' ');

const sha256 = (value: string) => createHash('sha256').update(value).digest('hex');

/** Digest of `term` as a supplied phrase -- the producer side of the mirror. */
function termDigest(term: string): string {
  const tokens = fold(term).match(/[a-z0-9]+/g) ?? [];
  return sha256(normalise(tokens.join(' ')));
}

/** Every 1..3-gram digest in `body` -- the consumer side of the mirror. */
function gramDigests(body: string): Set<string> {
  const tokens = fold(body).match(/[a-z0-9]+/g) ?? [];
  const out = new Set<string>();
  for (let i = 0; i < tokens.length; i += 1) {
    for (let n = 1; n <= PROTECTED_MAX_TOKENS && i + n <= tokens.length; n += 1) {
      out.add(sha256(normalise(tokens.slice(i, i + n).join(' '))));
    }
  }
  return out;
}

describe('protected terms', () => {
  // Premise guards. A digest list that is empty, malformed, or scanned by a
  // walker that never produces a matching gram passes over every content file
  // forever and reads as proof. None of the three can be checked against a real
  // term without publishing it, so they are checked against a fabricated
  // canary that behaves exactly like one.
  const CANARY = 'Zqxil Flumbernaut';

  it('the digest list is non-empty and well-formed', () => {
    expect(PROTECTED_SHA256.size).toBeGreaterThan(0);
    for (const digest of PROTECTED_SHA256) expect(digest).toMatch(/^[0-9a-f]{64}$/);
  });

  it('the scanner finds a protected term embedded in prose', () => {
    const body = `# A chapter\n\nThe work was done at ${CANARY} over two years.\n`;
    expect(gramDigests(body).has(termDigest(CANARY))).toBe(true);
  });

  it('the normaliser collapses inflections onto one digest', () => {
    // Plural, possessive, hyphenated and accented spellings must all red on the
    // digest of the base term -- otherwise the guard is a spelling test, not a
    // name test.
    const accented = CANARY.replace('u', 'ü');
    for (const variant of [`${CANARY}s`, `${CANARY}'s`, CANARY.replace(' ', '-'), accented]) {
      const body = `A line naming ${variant} in passing.\n`;
      expect(gramDigests(body).has(termDigest(CANARY)), variant).toBe(true);
    }
  });

  it('the scanner does not flag unrelated prose', () => {
    const body = 'A paragraph about agents, prompts, reviews and measured token counts.\n';
    const hits = [...gramDigests(body)].filter((digest) => PROTECTED_SHA256.has(digest));
    expect(hits).toEqual([]);
  });

  it.each(CONTENT_FILES)('%s: names no protected term', (path) => {
    const hits = [...gramDigests(read(path))].filter((digest) => PROTECTED_SHA256.has(digest));
    // The digest is not echoed: a failure message is copied into issues and chat
    // far more casually than a source file, and the digest confirms a guess.
    expect(hits.length, `${path}: names a protected term`).toBe(0);
  });
});

// The six rungs render on /journey/ from `RUNGS` itself, so the NAMES cannot
// drift. What can drift is the metadata beside them: `RUNG_META` in
// `src/pages/journey/index.astro` is a hand-written Record, and `astro build`
// does not typecheck, so a seventh rung added to the enum reaches the build as
// an opaque "Cannot read properties of undefined" at render time. This is the
// legible half of that gate — it names the rung that has no row.
describe('the rung ladder reaches /journey/', () => {
  const rungs = (() => {
    const config = read(join('src', 'content.config.ts'));
    const decl = config.match(/^export const RUNGS = \[([^\]]*)\]/m);
    expect(decl, 'no RUNGS in src/content.config.ts').not.toBeNull();
    return [...decl![1].matchAll(/'([^']+)'/g)].map((m) => m[1]);
  })();

  const page = read(join('src', 'pages', 'journey', 'index.astro'));
  const meta = page.match(/const RUNG_META[^=]*= \{([\s\S]*?)\n\};/);

  it('there are rungs to check, and a table to check them against', () => {
    expect(rungs.length).toBeGreaterThan(1);
    expect(meta, 'no RUNG_META in src/pages/journey/index.astro').not.toBeNull();
  });

  it.each(rungs)('%s: has a date and a unit handed over', (rung) => {
    const row = meta![1].match(new RegExp(`^\\s*${rung}: \\{([^}]*)\\}`, 'm'));
    expect(row, `${rung} is in RUNGS with no RUNG_META row`).not.toBeNull();
    expect(row![1], `${rung}: no from: date`).toMatch(/from: '\d{4}-\d{2}'/);
    expect(row![1], `${rung}: no unit handed over`).toMatch(/unit: '[^']+'/);
  });

  it('the table renders from the enum rather than hand-typed rows', () => {
    expect(page, '/journey/ does not import RUNGS').toMatch(
      /import \{ RUNGS \} from '\.\.\/\.\.\/content\.config'/,
    );
    expect(page, '/journey/ does not map its table over RUNGS').toMatch(/RUNGS\.map\(/);
  });
});

const WRONG_CHAPTER = join(JOURNEY, '90-what-i-got-wrong.md');

// A regression guard, not a correctness check: correctness is the verified read
// against `sources/`, and this only reds when a later edit drops or alters one.
const DATED_SPINE = [
  { date: '2025-12-05', what: 'the shell wrapper failed on every command', mark: /`exit -1`[\s\S]*`pid: -1`/ },
  { date: '2025-12-05', what: 'edits reported success on an untouched file', mark: /CVE-2025-59944/ },
  { date: '2025-12-05', what: 'a shown diff was absent from disk until applied', mark: /`\+380`-line diff/ },
  { date: '2025-12-05', what: 'agent plans lived outside the repo', mark: /internal application data/ },
  { date: '2026-02-08', what: 'the subagent limitation that ended the era', mark: /same conversation context/ },
  { date: '2026-02-07', what: 'the free alternatives that priced the switch', mark: /OpenCode, Cline and Aider/ },
];

describe('the dated spine of 90-what-i-got-wrong', () => {
  const body = read(WRONG_CHAPTER);

  it('there is a spine to check', () => {
    expect(DATED_SPINE.length).toBe(6);
    expect(DATED_SPINE.filter((row) => row.date === '2025-12-05')).toHaveLength(4);
  });

  it.each(DATED_SPINE)('$date: $what', ({ date, mark }) => {
    expect(body, `${date} no longer appears in the chapter`).toContain(date);
    expect(body, `the ${date} evidence no longer matches ${mark}`).toMatch(mark);
  });
});


// inc7b Stage 3a -- the mining falsifiers. Falsifier (a), one dated quote per
// atom, shipped in Stage 1 above. (b), (c) and (d) are here, each reshaped where
// the spec's premise did not hold; the reasons are in the plan's Stage 3 addendum.

const TOPICS = contentFiles(TOPIC_DIR);

/** A quoted `## Evidence` line as one comparable string: no `>`, no bracketed
 *  date, no wrapping quotes, whitespace collapsed. */
function quotedLine(evidence: string): string {
  return evidence
    .split('\n')
    .filter((line) => /^\s*>/.test(line))
    .map((line) => line.replace(/^\s*>\s?/, ''))
    .join(' ')
    .replace(/\[\d{4}-\d{2}(-\d{2})?(\.\.\d{4}-\d{2}(-\d{2})?)?\]/, '')
    .replace(/^\s*["“]|["”]\s*$/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

const collapse = (body: string) => body.replace(/\s+/g, ' ');

// (b) Evidence-verbatim. `source_chapter` is the chapter an atom was MINED FOR
// -- Stage 4's transclusion key -- not where its quote came from, so it cannot
// be the target here. `quote_from` names the public in-repo file the line is
// reproduced from; an atom without one was quoted from a private source, is
// verified against the private index at authoring time, and is SKIPPED by name
// rather than passed silently.
describe('evidence provenance', () => {
  // The skip is honest -- it keys on the ABSENCE of `quote_from`, per atom, not on
  // a hand-maintained name list. But a corpus of skips is a corpus with no gate:
  // drop `quote_from` from every atom and every case below skips, the describe
  // passes green, and nothing is verified. This floor reds on that. It anchors on
  // the atoms the gate CHECKS, which publishing more quotes grows -- never on the
  // violations it finds, which a fix would drain to zero.
  it('at least one atom is actually verbatim-checked', () => {
    const checked = ATOMS.filter((path) => frontmatter(read(path), 'quote_from'));
    expect(
      checked.length,
      'every atom skips: no `quote_from` anywhere, so this gate verifies nothing',
    ).toBeGreaterThan(0);
  });

  for (const path of ATOMS) {
    const from = frontmatter(read(path), 'quote_from');
    const label = from
      ? `${path}: the quoted line is verbatim in ${from}`
      : `${path}: quoted from a private source -- verified against the private index, not here`;

    it.skipIf(!from)(label, () => {
      const evidence = section(read(path), 'Evidence');
      expect(evidence, `${path}: no \`## Evidence\` section`).toBeDefined();
      const quote = quotedLine(evidence!);
      expect(quote.length, `${path}: the quote is empty once the date is stripped`).toBeGreaterThan(
        20,
      );
      expect(
        collapse(read(from!)),
        `${path}: \`quote_from: ${from}\` does not contain the quoted line`,
      ).toContain(quote);
    });
  }
});

// (c) Mined material is translated, never pasted. Scoped to the corpus, not to
// all of content/**: `content/artifacts/agent-loop.md` reproduces Estonian
// prompt lines beside their glosses on purpose and says so in its own body, and
// an allowlist would be where every later exception went quietly.
describe('the mined corpus is in English', () => {
  const CORPUS = [...ATOMS, ...SIDECARS, ...TOPICS];
  // Estonian function words with no English reading, plus the four vowels that
  // exist in no English word. Two markers on one line, or one diacritic, is the
  // threshold -- a single shared token is not evidence of a language.
  const MARKERS = [
    'ja', 'ning', 'kui', 'siis', 'peale', 'teises', 'uus', 'mitte', 'kõik',
    'või', 'aga', 'oli', 'olen', 'teha', 'vaja', 'kopeerida', 'poolset',
  ];
  const marker = new RegExp(`(?<![A-Za-zÀ-ÿ])(${MARKERS.join('|')})(?![A-Za-zÀ-ÿ])`, 'gi');

  it('there is a corpus to sweep, and markers to sweep it with', () => {
    expect(CORPUS.length, 'no atoms, sidecars or topics found').toBeGreaterThan(0);
    expect(MARKERS.length).toBeGreaterThan(4);
  });

  it.each(CORPUS)('%s: carries no Estonian line', (path) => {
    const hits: string[] = [];
    read(path)
      .split('\n')
      .forEach((line, i) => {
        const distinct = new Set([...line.matchAll(marker)].map((m) => m[1].toLowerCase()));
        if (distinct.size >= 2 || /[õäöü]/i.test(line)) hits.push(`${i + 1}: ${[...distinct]}`);
      });
    expect(hits, `${path}: Estonian on line(s) ${hits.join('; ')}`).toEqual([]);
  });
});

// (d) The lecture is 90 minutes. The spec's 82..90 band is a corpus-COMPLETENESS
// property and cannot pass while the corpus is being built, so only the ceiling
// ships now; the >= 82 floor arms at the inc6b content freeze. The audience must
// be non-empty first, or the sum is trivially under any ceiling.
describe('the university cut fits the lecture', () => {
  const MINUTES_CEILING = 90;
  const cut = ATOMS.filter((path) => /\buniversity\b/.test(frontmatter(read(path), 'audience') ?? ''));

  it('the university audience is non-empty', () => {
    expect(cut.length, 'no atom carries `audience: [... university ...]`').toBeGreaterThan(0);
  });

  it(`the university cut runs at most ${MINUTES_CEILING} minutes`, () => {
    const total = cut.reduce((sum, path) => sum + Number(frontmatter(read(path), 'minutes')), 0);
    expect(Number.isFinite(total), 'an atom in the cut has a non-numeric `minutes`').toBe(true);
    expect(total, `the university cut sums to ${total} minutes`).toBeLessThanOrEqual(MINUTES_CEILING);
  });
});
