import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

// The content gate. Three assertions over the authored markdown, each one the
// executable form of a line in `.claude/rules/content-writing.md`:
//   (a) `artifact: present` <=> a non-empty `## Artifact` body   (evidence rule)
//   (b) every chapter carries `## What didn't work`               (anti-hype rule)
//   (c) no content file uses the banned vocabulary                (anti-hype rule)
// Plus two mirror tests: each hand-copied constant is read back out of BOTH of
// its homes and compared, so a divergence reds instead of rotting quietly.

const CONTENT = 'content';
const JOURNEY = join(CONTENT, 'journey');

// Neither file is a chapter: `00-experiments.md` is the one-line-per-repo list
// and `README.md` is generated by scripts/timeline-from-git.py. Both are
// excluded from the Astro journey collection for the same reason (no
// frontmatter), so (a) and (b) cannot apply to them.
const NOT_A_CHAPTER = new Set(['00-experiments.md', 'README.md']);

// Mirrors the banned list in `.claude/rules/content-writing.md` §Anti-hype.
// Hardcoded on purpose: the `banned list matches the rule file` test below
// compares the two, so a reworded rule bullet reds THAT test rather than
// taking this assertion down with it.
const BANNED = [
  '10x',
  'game-changer',
  'game changer',
  'revolution',
  'revolutionary',
  'anyone can',
  'in minutes',
  'no code needed',
  'effortless',
  'magic',
];

/** Every `.md` under content/, recursively, minus the generated index. */
function contentFiles(dir = CONTENT): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return contentFiles(path);
    if (!entry.name.endsWith('.md')) return [];
    if (path === join(JOURNEY, 'README.md')) return [];
    return [path];
  });
}

/** The 13 journey chapters, by path. */
function chapters(): string[] {
  return readdirSync(JOURNEY)
    .filter((name) => name.endsWith('.md') && !NOT_A_CHAPTER.has(name))
    .sort()
    .map((name) => join(JOURNEY, name));
}

const read = (path: string) => readFileSync(path, 'utf8');

/** The value of a single frontmatter key, or undefined. */
function frontmatter(body: string, key: string): string | undefined {
  const block = body.match(/^---\n([\s\S]*?)\n---\n/);
  if (!block) return undefined;
  const line = block[1].match(new RegExp(`^${key}:\\s*(.*)$`, 'm'));
  return line?.[1].trim();
}

/** The body under `## <heading>`, up to the next `## ` or EOF. */
function section(body: string, heading: string): string | undefined {
  const start = body.match(new RegExp(`^## ${heading}\\s*$`, 'm'));
  if (start?.index === undefined) return undefined;
  const after = body.slice(start.index + start[0].length);
  const next = after.search(/^## /m);
  return (next === -1 ? after : after.slice(0, next)).trim();
}

/**
 * A whole-word match for `word`, safe for entries that begin or end with a
 * non-word character. `\b` cannot express a boundary next to `+` or `.`, so a
 * future banned entry like `C++` would compile to a regex that never matches —
 * unenforced, and silent about it. Explicit lookarounds have no such hole.
 */
function bounded(word: string): string {
  const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return `(?<![A-Za-z0-9])${escaped}(?![A-Za-z0-9])`;
}

const CONTENT_FILES = contentFiles();
const CHAPTERS = chapters();

describe('premise guards', () => {
  // A vacuous suite passes forever. Each of the three assertions below iterates
  // over a set that could be empty by accident (a moved directory, an emptied
  // list); these fail loudly when it is.
  it('has a non-empty banned-vocabulary list', () => {
    expect(BANNED.length).toBeGreaterThan(0);
  });

  it('found the journey chapters', () => {
    expect(CHAPTERS.length).toBeGreaterThan(0);
  });

  it('found the content files to sweep', () => {
    expect(CONTENT_FILES.length).toBeGreaterThan(0);
  });
});

describe('evidence rule', () => {
  // (a) The frontmatter enum and the prose must agree. `present` claims an
  // artifact block, so the section body must carry one; `pending` is the stub
  // state timeline-from-git.py emits — heading, nothing under it. Checking only
  // that the heading exists would be vacuous (every chapter has one).
  it.each(CHAPTERS)('%s: artifact frontmatter matches the Artifact body', (path) => {
    const body = read(path);
    const declared = frontmatter(body, 'artifact');
    // The enum is also the Zod schema's, and `astro build` runs before vitest in
    // `make check` — but assert it here too so `make test` stands on its own and
    // a typo cannot fall through to the `pending` branch below.
    expect([`present`, `pending`], `${path}: \`artifact: ${declared}\``).toContain(declared);

    const artifact = section(body, 'Artifact');
    expect(artifact, `${path}: no \`## Artifact\` heading`).toBeDefined();

    if (declared === 'present') {
      expect(artifact, `${path}: \`artifact: present\` but the section is empty`).not.toBe('');
    } else {
      expect(artifact, `${path}: \`artifact: ${declared}\` but the section has a body`).toBe('');
    }
  });
});

describe('anti-hype rule', () => {
  // (b) Failures get equal billing: the heading is the structural guarantee.
  it.each(CHAPTERS)("%s: has a `## What didn't work` section", (path) => {
    expect(section(read(path), "What didn't work")).toBeDefined();
  });

  // (c) Word-boundary, case-insensitive, across every authored content file --
  // not just the chapters -- because the rule's own `paths:` is content/**/*.md.
  it.each(CONTENT_FILES)('%s: uses no banned vocabulary', (path) => {
    const body = read(path);
    const hits = BANNED.filter((word) => new RegExp(bounded(word), 'i').test(body));
    expect(hits, `${path}: banned vocabulary`).toEqual([]);
  });
});

describe('mirrored constants', () => {
  // The banned list above is a hand-copy of the rule file's. Parse the rule's
  // bullet and compare the two sets, so adding a word in one place and not the
  // other reds here rather than silently going unenforced.
  it('banned list matches `content-writing.md` §Anti-hype', () => {
    const rule = read(join('.claude', 'rules', 'content-writing.md'));
    const bullet = rule.match(/^- \*\*Banned vocabulary\*\*[^\n]*\n(?:[ \t]+[^\n]*\n)*/m);
    expect(bullet, 'could not find the `Banned vocabulary` bullet').not.toBeNull();

    const fromRule = [...bullet![0].matchAll(/`([^`]+)`/g)].map((m) => m[1]);
    expect(new Set(fromRule)).toEqual(new Set(BANNED));
  });

  // `MIN_COMMITS` lives in the generator and is hand-copied into the site's
  // shared timeline lib (which uses it to build the "also tried" list). They
  // must not drift: the two files would then disagree about what counts as a
  // chapter. The site half moved out of `src/pages/journey/index.astro` into
  // `src/lib/timeline.ts` in inc4 Stage 2, so this regex tracks the new home.
  it('MIN_COMMITS matches between the generator and the timeline lib', () => {
    const script = read(join('scripts', 'timeline-from-git.py'));
    const lib = read(join('src', 'lib', 'timeline.ts'));

    const fromScript = script.match(/^MIN_COMMITS\s*=\s*(\d+)/m);
    const fromLib = lib.match(/^export const MIN_COMMITS\s*=\s*(\d+);/m);
    expect(fromScript, 'no MIN_COMMITS in timeline-from-git.py').not.toBeNull();
    expect(fromLib, 'no MIN_COMMITS in src/lib/timeline.ts').not.toBeNull();

    expect(fromLib![1]).toBe(fromScript![1]);
  });

  // `content/timeline.json` is generated, so these assert the GENERATOR's two
  // honesty rules rather than hand-authored prose.
  //
  // (1) End-dates exclude AI-config-only commits. A `chore(claude):` deny-list
  //     sweep touched 13 repos on 2026-09-06; counting it made every one of them
  //     claim activity that day. `dewpoint`'s pinned date is the discriminating
  //     case: it moves 14 months if the exclusion pathspec is dropped.
  // (2) `dewpoint-app` (the Python original) and `dewpoint-ts` (the Node port
  //     made to deploy on Vercel) are ONE project, so they collapse into a
  //     single `dewpoint` row via the generator's REPO_GROUPS map.
  //
  // The pinned dates are data assertions naming a specific value on purpose: if
  // one of these repos is legitimately reactivated, this test reds and the line
  // has to be re-pinned. That is real work being flagged, not a false alarm.
  describe('timeline.json honesty', () => {
    const rows: Array<{
      repo: string;
      first_commit: string;
      last_commit: string;
      commits: number;
      stage: string;
    }> = JSON.parse(read(join(CONTENT, 'timeline.json')));

    // Vacuity anchors: a parser that silently yields [] or a truncated array
    // would let every assertion below pass by looping over nothing.
    it('parses to the full 14-row corpus', () => {
      expect(Array.isArray(rows)).toBe(true);
      expect(rows).toHaveLength(14);
    });

    it('dates the dewpoint row past the AI-config sweep, not on it', () => {
      const dewpoint = rows.find((r) => r.repo === 'dewpoint');
      expect(dewpoint, 'no dewpoint row in timeline.json').toBeDefined();
      // Drop `:(exclude).claude/**` & friends from the generator and this
      // becomes 2026-09-06 -- the sweep date.
      expect(dewpoint!.last_commit).toBe('2026-06-25');
      expect(dewpoint!.first_commit).toBe('2025-07-15');
    });

    it('merges the two dewpoint repos into one row', () => {
      expect(rows.filter((r) => r.repo.startsWith('dewpoint'))).toHaveLength(1);
      for (const gone of ['dewpoint-app', 'dewpoint-ts']) {
        expect(rows.some((r) => r.repo === gone), `${gone} still a row`).toBe(false);
      }
      // 4 commits in the Python original + 102 in the TS port.
      expect(rows.find((r) => r.repo === 'dewpoint')!.commits).toBe(106);
    });

    it('leaves only the genuinely-active repos dated on the sweep day', () => {
      const onSweepDay = rows.filter((r) => r.last_commit === '2026-09-06').map((r) => r.repo);
      expect(onSweepDay.sort()).toEqual(['crash-dash', 'dotfiles']);
    });

    it('never ends a repo before it started, or in the future', () => {
      for (const r of rows) {
        expect(r.first_commit <= r.last_commit, `${r.repo} ends before it starts`).toBe(true);
        expect(r.last_commit <= '2026-09-06', `${r.repo} ends in the future`).toBe(true);
      }
    });
  });
});

// (d) Provenance: every case-study artifact names the relative path or commit it
// was rewritten from. This is the executable form of the `content/case-study/
// crash-dash/**` admission row ("each with its origin path and date"). It lives
// here rather than in the Zod schema because `index.md` is the landing body, not
// an artifact, and carries no origin -- an always-required schema key would red
// on it. The population assertion is not decoration: without it a rename of the
// directory would empty ARTIFACTS and the guard would pass over nothing.
const CASE_STUDY = join(CONTENT, 'case-study', 'crash-dash');

// The landing body, excluded by exact path rather than by filename: a nested
// `<sub>/index.md` would still be a real artifact with its own route, and an
// `endsWith('index.md')` test would drop it from the check while the route
// shipped it.
const LANDING = join(CASE_STUDY, 'index.md');
const ARTIFACTS = contentFiles(CASE_STUDY).filter((path) => path !== LANDING);

// The admission row says "each with its origin path AND date", so both halves
// are asserted -- an `origin`-only guard leaves a missing `date` green in every
// gate (Zod has it optional so index.md can omit it).
describe('case-study provenance', () => {
  it('there are artifacts to check', () => {
    expect(ARTIFACTS.length, `no artifacts found under ${CASE_STUDY}`).toBeGreaterThan(0);
  });

  it.each(ARTIFACTS)('%s: carries `origin` and `date` frontmatter', (path) => {
    const body = read(path);

    const origin = frontmatter(body, 'origin');
    expect(origin, `${path}: no \`origin:\` in frontmatter`).toBeDefined();
    expect(origin, `${path}: empty \`origin:\``).not.toBe('');

    const date = frontmatter(body, 'date');
    expect(date, `${path}: no \`date:\` in frontmatter`).toBeDefined();
    expect(date, `${path}: \`date:\` is not an ISO day`).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });
});
