import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

// The content gate. Three assertions over the authored markdown, each one the
// executable form of a line in `.claude/rules/content-writing.md`:
//   (a) `artifact: present` <=> a non-empty `## Artifact` body   (evidence rule)
//   (b) every chapter carries `## What didn't work`               (anti-hype rule)
//   (c) no content file uses the banned vocabulary                (anti-hype rule)
// Plus two mirror tests: each hand-copied constant is read back out of BOTH of
// its homes and compared, so a divergence reds instead of rotting quietly.

const CONTENT = 'content';
const JOURNEY = join(CONTENT, 'journey');

// Neither file is a chapter: `00-experiments.md` is the one-line-per-repo list
// and `README.md` is generated by scripts/timeline-from-git.py. Both are
// excluded from the Astro journey collection for the same reason (no
// frontmatter), so (a) and (b) cannot apply to them.
const NOT_A_CHAPTER = new Set(['00-experiments.md', 'README.md']);

// Mirrors the banned list in `.claude/rules/content-writing.md` §Anti-hype.
// Hardcoded on purpose: the `banned list matches the rule file` test below
// compares the two, so a reworded rule bullet reds THAT test rather than
// taking this assertion down with it.
const BANNED = [
  '10x',
  'game-changer',
  'game changer',
  'revolution',
  'revolutionary',
  'anyone can',
  'in minutes',
  'no code needed',
  'effortless',
  'magic',
];

/** Every `.md` under content/, recursively, minus the generated index. */
function contentFiles(dir = CONTENT): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return contentFiles(path);
    if (!entry.name.endsWith('.md')) return [];
    if (path === join(JOURNEY, 'README.md')) return [];
    return [path];
  });
}

/** The 13 journey chapters, by path. */
function chapters(): string[] {
  return readdirSync(JOURNEY)
    .filter((name) => name.endsWith('.md') && !NOT_A_CHAPTER.has(name))
    .sort()
    .map((name) => join(JOURNEY, name));
}

const read = (path: string) => readFileSync(path, 'utf8');

/** The value of a single frontmatter key, or undefined. */
function frontmatter(body: string, key: string): string | undefined {
  const block = body.match(/^---\n([\s\S]*?)\n---\n/);
  if (!block) return undefined;
  const line = block[1].match(new RegExp(`^${key}:\\s*(.*)$`, 'm'));
  return line?.[1].trim();
}

/** The body under `## <heading>`, up to the next `## ` or EOF. */
function section(body: string, heading: string): string | undefined {
  const start = body.match(new RegExp(`^## ${heading}\\s*$`, 'm'));
  if (start?.index === undefined) return undefined;
  const after = body.slice(start.index + start[0].length);
  const next = after.search(/^## /m);
  return (next === -1 ? after : after.slice(0, next)).trim();
}

const CONTENT_FILES = contentFiles();
const CHAPTERS = chapters();

describe('premise guards', () => {
  // A vacuous suite passes forever. Each of the three assertions below iterates
  // over a set that could be empty by accident (a moved directory, an emptied
  // list); these fail loudly when it is.
  it('has a non-empty banned-vocabulary list', () => {
    expect(BANNED.length).toBeGreaterThan(0);
  });

  it('found the journey chapters', () => {
    expect(CHAPTERS.length).toBeGreaterThan(0);
  });

  it('found the content files to sweep', () => {
    expect(CONTENT_FILES.length).toBeGreaterThan(0);
  });
});

describe('evidence rule', () => {
  // (a) The frontmatter enum and the prose must agree. `present` claims an
  // artifact block, so the section body must carry one; `pending` is the stub
  // state timeline-from-git.py emits — heading, nothing under it. Checking only
  // that the heading exists would be vacuous (every chapter has one).
  it.each(CHAPTERS)('%s: artifact frontmatter matches the Artifact body', (path) => {
    const body = read(path);
    const declared = frontmatter(body, 'artifact');
    expect(declared, `${path}: no \`artifact:\` in frontmatter`).toBeDefined();

    const artifact = section(body, 'Artifact');
    expect(artifact, `${path}: no \`## Artifact\` heading`).toBeDefined();

    if (declared === 'present') {
      expect(artifact, `${path}: \`artifact: present\` but the section is empty`).not.toBe('');
    } else {
      expect(artifact, `${path}: \`artifact: ${declared}\` but the section has a body`).toBe('');
    }
  });
});

describe('anti-hype rule', () => {
  // (b) Failures get equal billing: the heading is the structural guarantee.
  it.each(CHAPTERS)("%s: has a `## What didn't work` section", (path) => {
    expect(section(read(path), "What didn't work")).toBeDefined();
  });

  // (c) Word-boundary, case-insensitive, across every authored content file --
  // not just the chapters -- because the rule's own `paths:` is content/**/*.md.
  it.each(CONTENT_FILES)('%s: uses no banned vocabulary', (path) => {
    const body = read(path);
    const hits = BANNED.filter((word) =>
      new RegExp(`\\b${word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'i').test(body),
    );
    expect(hits, `${path}: banned vocabulary`).toEqual([]);
  });
});

describe('mirrored constants', () => {
  // The banned list above is a hand-copy of the rule file's. Parse the rule's
  // bullet and compare the two sets, so adding a word in one place and not the
  // other reds here rather than silently going unenforced.
  it('banned list matches `content-writing.md` §Anti-hype', () => {
    const rule = read(join('.claude', 'rules', 'content-writing.md'));
    const bullet = rule.match(/^- \*\*Banned vocabulary\*\*[^\n]*\n(?:[ \t]+[^\n]*\n)*/m);
    expect(bullet, 'could not find the `Banned vocabulary` bullet').not.toBeNull();

    const fromRule = [...bullet![0].matchAll(/`([^`]+)`/g)].map((m) => m[1]);
    expect(new Set(fromRule)).toEqual(new Set(BANNED));
  });

  // `MIN_COMMITS` lives in the generator and is hand-copied into the site's
  // journey index (which uses it to build the "also tried" list). They must not
  // drift: the two files would then disagree about what counts as a chapter.
  it('MIN_COMMITS matches between the generator and the journey index', () => {
    const script = read(join('scripts', 'timeline-from-git.py'));
    const page = read(join('src', 'pages', 'journey', 'index.astro'));

    const fromScript = script.match(/^MIN_COMMITS\s*=\s*(\d+)/m);
    const fromPage = page.match(/^const MIN_COMMITS\s*=\s*(\d+);/m);
    expect(fromScript, 'no MIN_COMMITS in timeline-from-git.py').not.toBeNull();
    expect(fromPage, 'no MIN_COMMITS in journey/index.astro').not.toBeNull();

    expect(fromPage![1]).toBe(fromScript![1]);
  });
});
