// Shared helpers for the split content and measurements suites. Not a
// `.test.ts` on purpose: vitest's `include` is `tests/**/*.test.ts`, so this
// module never runs as a suite of its own.

import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { expect } from 'vitest';

import eras_ from '../content/measurements/data/eras.json';

// ── Content suite helpers ─────────────────────────────────────────────────────
//
// The content gate. Three assertions over the authored markdown, each one the
// executable form of a line in `.claude/rules/content-writing.md`:
//   (a) `artifact: present` <=> a non-empty `## Artifact` body   (evidence rule)
//   (b) every chapter carries `## What didn't work`               (anti-hype rule)
//   (c) no content file uses the banned vocabulary                (anti-hype rule)
// Plus one prose-vs-source test: the rule file's banned-vocabulary bullet is
// compared to `src/lib/content-rules.ts`, so a divergence reds instead of
// rotting quietly.

export const CONTENT = 'content';
export const JOURNEY = join(CONTENT, 'journey');

// Neither file is a chapter: `00-experiments.md` is the one-line-per-repo list
// and `README.md` is generated by scripts/timeline-from-git.py. Both are
// excluded from the Astro journey collection for the same reason (no
// frontmatter), so (a) and (b) cannot apply to them.
const NOT_A_CHAPTER = new Set(['00-experiments.md', 'README.md']);


/** Every `.md` under content/, recursively, minus the generated index. */
export function contentFiles(dir = CONTENT): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return contentFiles(path);
    if (!entry.name.endsWith('.md')) return [];
    if (path === join(JOURNEY, 'README.md')) return [];
    return [path];
  });
}

/** The 13 journey chapters, by path. */
export function chapters(): string[] {
  return readdirSync(JOURNEY)
    .filter((name) => name.endsWith('.md') && !NOT_A_CHAPTER.has(name))
    .sort()
    .map((name) => join(JOURNEY, name));
}

export const read = (path: string) => readFileSync(path, 'utf8');

/** The value of a single frontmatter key, or undefined. */
export function frontmatter(body: string, key: string): string | undefined {
  const block = body.match(/^---\n([\s\S]*?)\n---\n/);
  if (!block) return undefined;
  const line = block[1].match(new RegExp(`^${key}:\\s*(.*)$`, 'm'));
  return line?.[1].trim();
}

/** The body under `## <heading>`, up to the next `## ` or EOF. */
export function section(body: string, heading: string): string | undefined {
  const start = body.match(new RegExp(`^## ${heading}\\s*$`, 'm'));
  if (start?.index === undefined) return undefined;
  const after = body.slice(start.index + start[0].length);
  const next = after.search(/^## /m);
  return (next === -1 ? after : after.slice(0, next)).trim();
}

/**
 * A whole-word match for `word`, safe for entries that begin or end with a
 * non-word character. `\b` cannot express a boundary next to `+` or `.`, so a
 * future banned entry like `C++` would compile to a regex that never matches —
 * unenforced, and silent about it. Explicit lookarounds have no such hole.
 */
export function bounded(word: string): string {
  const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return `(?<![A-Za-z0-9])${escaped}(?![A-Za-z0-9])`;
}

export const CONTENT_FILES = contentFiles();
export const CHAPTERS = chapters();

/** The `kind` enum as declared in the collection schema, not a hand-copy. */
export function artifactKinds(): string[] {
  const config = read(join('src', 'content.config.ts'));
  const decl = config.match(/^export const ARTIFACT_KINDS = \[([^\]]*)\]/m);
  expect(decl, 'no ARTIFACT_KINDS in src/content.config.ts').not.toBeNull();
  return [...decl![1].matchAll(/'([^']+)'/g)].map((m) => m[1]);
}

/** A `const` array as DECLARED in the collection schema, not a hand-copy. */
export function configEnum(name: string): string[] {
  const config = read(join('src', 'content.config.ts'));
  const decl = config.match(new RegExp(`^export const ${name} = \\[([^\\]]*)\\]`, 'm'));
  expect(decl, `no ${name} in src/content.config.ts`).not.toBeNull();
  return [...decl![1].matchAll(/'([^']+)'/g)].map((m) => m[1]);
}

export const ATOM_DIR = join(CONTENT, 'atoms');
export const TOPIC_DIR = join(CONTENT, 'topics');
export const ATOMS = contentFiles(ATOM_DIR);

export const SIDECAR_DIR = join(CONTENT, 'sidecars');
export const SIDECARS = contentFiles(SIDECAR_DIR);

// The `root page links every top-level route` guard used to live in the
// content suite. inc8 moved it to `tests/nav.test.ts`: three doors means a
// route is reachable via the root page OR one of the three door indexes, so the
// assertion could not stay pinned to src/pages/index.astro alone.

// ── Measurements suite helpers ────────────────────────────────────────────────
//
// Hermetic over the COMMITTED eras.json — this suite never shells out to git and never
// reads the private full store. The generators (`make measurements`) talk to the config
// repo and the log trees; `scripts/measurements-public.py` redacts their output into the
// file pinned here, so the gate stays runnable on a machine that has neither.
//
// Three kinds of assertion:
//   (1) REDACTION — the boundary itself. These red when an absolute volume or a money
//       figure reappears anywhere public, which is the failure that actually matters.
//   (2) SHAPE — the era list's contract. These red when a parser or schema change
//       collapses the list, drops an era, or flattens a typed field.
//   (3) DATA PINS — commit counts, date ranges and coverage ratios, recomputed by the
//       generators before they were pinned here. These red when the sources move.
export const document = eras_ as unknown as {
  schema: number;
  redaction: { policy: string; bearingTools: number; totalTools: number; withheld: string[]; note: string };
  eras: any[];
  sttFaster: Record<string, any>;
};

// Narrative order, NOT chronological — the list has never been sorted by
// `gitStart` (codex 2025-08-28 precedes cursor 2025-07-31), and gemini's
// 2025-07-04 is the earliest of any tool era while sitting second-to-last.
// What the order does say: the chat era precedes every tool that left a
// record, and gemini is the CLI-agent bridge into Claude Code. Nothing pins
// order against dates; the only date pins are within-era (gitStart <= gitEnd).
export const SPEC_ORDER = ['chat', 'copilot', 'continue', 'codex', 'cursor', 'gemini', 'claude-code'];

export const byId = (id: string) => document.eras.find((e) => e.id === id)!;

export interface Leaf {
  path: string;
  key: string;
  value: unknown;
}

export function leaves(node: unknown, path = '', key = ''): Leaf[] {
  if (Array.isArray(node)) return node.flatMap((v, i) => leaves(v, `${path}[${i}]`, key));
  if (node && typeof node === 'object') {
    return Object.entries(node).flatMap(([k, v]) => leaves(v, path ? `${path}.${k}` : k, k));
  }
  return [{ path, key, value: node }];
}

export const MEAS = join(process.cwd(), 'content', 'measurements');
export const measFiles = () => readdirSync(MEAS).filter((f) => f.endsWith('.md')).sort();
export const readMeas = (file: string) => readFileSync(join(MEAS, file), 'utf8');
