#!/usr/bin/env python3
"""Reduce the full measurement store to the PUBLISHABLE one. The redaction boundary.

Usage: python3 scripts/measurements-public.py

    sources/measurements/eras-full.json   (gitignored, generated by the other
                                           scripts/measurements-*.py)
              |
              |  this script
              v
    content/measurements/data/eras.json   (committed, public)

The policy, in one line: **publish states, dates and shares; never an absolute volume
and never a money figure.**

Why the boundary exists at all. The finding this repo needs from the measurement pass is
that most of these tools keep no usable receipts -- one of them, the chat era, kept
nothing at all -- and that the eras OVERLAP rather than succeed one another. Neither claim needs a token total, and both survive intact without
one. What a token total would add is a public statement about how much personal
AI-coding happened and when -- which is nobody's business, and reads differently from
the finding it sits next to. The absolute store stays private; this file is the only
thing that crosses into the tree.

What crosses:

  states       availability.tokens (yes/floor/none), counts, skills
  dates        git ranges, log ranges, the onset block (dates only, already public),
               and an era's authored date BRACKET plus the method that produced it --
               `dateMethod` is what lets the page label an estimate as one
  shares       each token-bearing era's fraction of the combined floor, 4 decimals
  ratios       coverage and split fractions -- "4.86% of bubbles carry a count",
               never the raw pair behind it
  small counts structural, non-volume: workspaces seen, header formats, models,
               config commits (already public in the timeline), skill files

What does not, ever:

  every token count, every session/message/turn/file count, every USD figure,
  availability.cost and the whole metrics.cost block.

The rule is enforced by a scan at the end of this script rather than by care: the
emitted document is walked, and any integer above ABSOLUTE_LIMIT or any key on the
banned list aborts the write. A regenerated era that grows a new absolute field fails
loudly here instead of leaking quietly.

Deterministic: sorted keys, no timestamps of its own.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FULL = ROOT / "sources" / "measurements" / "eras-full.json"
PUBLIC = ROOT / "content" / "measurements" / "data" / "eras.json"

# No integer this large is a state, a date part, a small structural count or a share.
# Anything bigger is a volume, and a volume is what this boundary exists to stop.
ABSOLUTE_LIMIT = 10_000

# Substrings that mark a key as being ABOUT tokens or money. A string, a date or a
# boolean under such a key is a state and crosses freely ("tokens": "floor",
# "firstToken": "2026-02-28", "costFieldPresent": false). A NUMBER under one does not,
# unless it is a fraction in [0, 1] -- i.e. a share, which is the only numeric form
# tokens and money are allowed to take in public.
BANNED_KEY_PARTS = (
    "cost",
    "usd",
    "token",
    "cachecreation",
    "cacheread",
)


def share_inputs(era: dict) -> int | None:
    """The era's three-class headline sum, from its own metrics shape. Used ONLY to
    compute shares; the sum itself never reaches the public document."""
    metrics = era.get("metrics") or {}
    match era["id"]:
        case "continue":
            t = metrics["tokens"]
            return t["promptTokens"] + t["generatedTokens"]
        case "codex":
            t = metrics["tokens"]
            # cached_input / reasoning_output are SUBSETS of these two; adding either
            # double-counts.
            return t["input_tokens"] + t["output_tokens"]
        case "cursor":
            t = metrics["tokens"]
            return t["input"] + t["output"]
        case "claude-code":
            sides = 0
            for side in ("main", "subagent"):
                t = metrics[side]["tokens"]
                sides += t["input"] + t["cacheCreation"] + t["output"]
            return sides
        case _:
            return None


def ratio(numerator: float, denominator: float) -> float | None:
    return round(numerator / denominator, 4) if denominator else None


def coverage(era: dict) -> dict:
    """Per-era ratios: everything the narrative needs to qualify a figure, expressed as
    a fraction so no absolute rides along."""
    m = era.get("metrics") or {}
    match era["id"]:
        case "copilot":
            return {
                "workspacesWithChat": m["workspacesWithChat"],
                "workspacesTotal": m["workspacesTotal"],
                "tokenFieldPresent": m["tokenFieldPresent"],
                "costFieldPresent": m["costFieldPresent"],
            }
        case "continue":
            events = m["byProvider"]["events"]
            total = sum(events.values())
            return {
                "localProviderEventShare": ratio(events.get("ollama", 0), total),
                "modelsSeen": m["tokens"]["models"],
                "mirrorAgrees": m["crossCheck"]["agrees"],
                "sessionLogEnd": m["sessions"]["end"],
            }
        case "codex":
            return {
                "loggingStart": m["tokens"]["loggingStart"],
                "partialLogging": m["tokens"]["partialLogging"],
                "rolloutsWithTokenShare": ratio(
                    m["tokens"]["filesWithTokens"], m["files"]
                ),
                "humanPromptShare": ratio(m["humanPrompts"], m["prompts"]),
                "headerFormats": len(m["headerFormats"]),
            }
        case "cursor":
            return {
                "pricedBubbleShare": m["nonZeroBubbleFraction"],
                "pricedBubblesAllAssistant": m["pricedBubbles"]
                == m["pricedBubblesAssistant"],
                "isFloor": m["isFloor"],
                "estimateSource": m["estimateSource"],
            }
        case "claude-code":
            main = m["main"]["tokens"]
            sub = m["subagent"]["tokens"]
            main_headline = main["input"] + main["cacheCreation"] + main["output"]
            sub_headline = sub["input"] + sub["cacheCreation"] + sub["output"]
            both = main_headline + sub_headline
            return {
                # How the era splits between the sessions I drove and the ones they
                # spawned -- the D1 finding, as a fraction.
                "mainShareOfEra": ratio(main_headline, both),
                "subagentShareOfEra": ratio(sub_headline, both),
                "sessionsUsingSubagentsShare": ratio(
                    m["subagent"]["parentSessions"], m["main"]["sessions"]
                ),
                # Reuse against the headline. >1 means more was re-read from cache than
                # was ever sent fresh -- the shape of the finding, without its size.
                "cacheReuseMultiple": ratio(main["cacheRead"] + sub["cacheRead"], both),
                "modelsSeen": len(
                    {
                        model
                        for side in ("main", "subagent")
                        for model in m[side]["perModel"]
                        if not model.startswith("<")
                    }
                ),
            }
        case "chat":
            # The era left no local record at all, so it has no coverage ratio. The one
            # number it does carry is a hardware ceiling, not a usage volume: how much
            # VRAM the home machine had, which is what bounded every local-model answer
            # of the period. Every count this corpus supports (threads, files) is a
            # statement about how much personal AI use happened, and stays private.
            return {"vramCeilingGiB": m["vramCeilingGiB"]}
        case _:
            return {}


def public_era(era: dict, share: float | None) -> dict:
    availability = dict(era["availability"])
    availability.pop("cost", None)  # the cost dimension does not cross
    provenance = {
        key: value for key, value in era["provenance"].items() if key != "cost"
    }
    out = {
        "id": era["id"],
        "tool": era["tool"],
        "group": era["group"],
        "availability": availability,
        "configDir": era["configDir"],
        "gitCommits": era["gitCommits"],
        "gitStart": era["gitStart"],
        "gitEnd": era["gitEnd"],
        "logStart": era["logStart"],
        "logEnd": era["logEnd"],
        # An era with neither record spans its authored bracket instead. `dateMethod`
        # crosses for EVERY era, not just that one: the page's badge is read from it, so
        # a "measured" range and an estimated bracket can never render alike.
        "dateLow": era.get("dateLow"),
        "dateHigh": era.get("dateHigh"),
        "dateMethod": era["dateMethod"],
        "provenance": provenance,
        "coverage": coverage(era),
        # None for Copilot: it logs no token field, so it has no share of the floor.
        # That null renders as an absence, never as a zero.
        "share": share,
    }
    if "skills" in era:
        out["skills"] = era["skills"]
    # Counts only, all far under the redaction ceiling; the audit re-checks them anyway.
    if "governance" in era:
        out["governance"] = era["governance"]
    if "onset" in era:
        out["onset"] = era["onset"]
    return out


def public_stt(stt: dict) -> dict:
    """The stt-faster corpus: file and generation counts, no tokens and no money in it
    to begin with. Carried across as-is minus nothing."""
    return dict(stt)


def audit(node: object, path: str = "") -> list[str]:
    """Walk the emitted document and report anything that looks like a volume or a
    price. This is the enforcement -- see the module docstring."""
    problems: list[str] = []
    if isinstance(node, dict):
        for key, value in node.items():
            here = f"{path}.{key}" if path else key
            lowered = key.lower()
            priced = any(part in lowered for part in BANNED_KEY_PARTS)
            if (
                priced
                and isinstance(value, (int, float))
                and not isinstance(value, bool)
                and not 0 <= value <= 1
            ):
                problems.append(f"{here}: {value} is a token or money quantity")
            problems += audit(value, here)
    elif isinstance(node, list):
        for index, value in enumerate(node):
            problems += audit(value, f"{path}[{index}]")
    elif isinstance(node, bool):
        pass  # bool is an int subclass; check it before the numeric branch
    elif isinstance(node, (int, float)) and abs(node) >= ABSOLUTE_LIMIT:
        problems.append(f"{path}: {node} is an absolute volume")
    return problems


def main() -> int:
    if not FULL.exists():
        print(
            f"error: {FULL.relative_to(ROOT)} missing — run `make measurements` first",
            file=sys.stderr,
        )
        return 1
    document = json.loads(FULL.read_text())
    eras = document["eras"]

    headlines = {era["id"]: share_inputs(era) for era in eras}
    floor = sum(value for value in headlines.values() if value)
    shares = {
        era_id: (round(value / floor, 4) if value and floor else None)
        for era_id, value in headlines.items()
    }

    bearing = [era for era in eras if era["availability"]["tokens"] != "none"]
    out = {
        "schema": 2,
        "redaction": {
            "policy": "states-dates-shares",
            "bearingTools": len(bearing),
            "totalTools": len(eras),
            "withheld": [
                "absolute token counts",
                "session, message, turn and file counts",
                "every cost figure and the cost availability state",
            ],
            "note": (
                "Shares are fractions of the combined floor across the token-bearing "
                "tools. The floor itself is not published, so no absolute is "
                "recoverable from them. The full store is private."
            ),
        },
        "eras": [public_era(era, shares[era["id"]]) for era in eras],
        "sttFaster": public_stt(document["sttFaster"]),
    }

    problems = audit(out)
    if problems:
        print("error: redaction audit failed — nothing written:", file=sys.stderr)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        return 1

    PUBLIC.parent.mkdir(parents=True, exist_ok=True)
    PUBLIC.write_text(json.dumps(out, indent=2, sort_keys=True) + "\n")
    print(
        f"wrote {PUBLIC.relative_to(ROOT)} — {len(out['eras'])} eras, "
        f"{len(bearing)} with a share, audit clean"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
