#!/usr/bin/env python3
"""Regenerate content/timeline.json, content/journey/README.md and missing chapter stubs from git.

Usage: python3 scripts/timeline-from-git.py [PROJECTS_DIR]   (default ~/projects)

Deterministic for a fixed set of repos: rerunning rewrites timeline.json and the index
byte-identically. Chapter stubs and 00-experiments.md are created only when absent.
Hand-maintain STAGE and EXCLUDE below; never hand-edit the generated files.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"
JOURNEY = CONTENT / "journey"
TIMELINE = CONTENT / "timeline.json"
INDEX = JOURNEY / "README.md"
EXPERIMENTS = JOURNEY / "00-experiments.md"
MIN_COMMITS = 5  # below this a repo is an experiment line, not a chapter

# Repos never scanned: tooling dirs, copied-not-modified course/lab material,
# other people's repos, this repo, and git worktrees (any name ending in -wt).
EXCLUDE = {
    "ai-coding-journey",
    "bin",
    "mybrain",
    "claude_skills",
    "arxiv-paper-curator",
    "01-claude-code-pm-course",
    "03-learn-claude-code",
    "09-learn-claude-code",
    "cookie-test1",
    "cafe-cursor-lab-materials",
    "Locked-Shields-PR-BT06-2026",
    "ls-sitrep",
    "autoresearch-ks",
    "Closaria",
    "Closaria-FE",
}

# Hand-maintained stage per repo. Unknown repos get "unassigned".
STAGE = {
    "hands-on-llm": "chat",
    "dewpoint-app": "chat",
    "dewpoint-ts": "chat",
    "docs-generator": "chat",
    "llm-eng-template": "chat",
    "kri-local-rag": "local-llm",
    "stt-faster": "local-llm",
    "xls-analyser": "first-agent",
    "gitlab-standup": "first-agent",
    "proj-mgmt": "first-agent",
    "token-monitor": "config-engineering",
    "dotfiles": "config-engineering",
    "claudeconf": "config-engineering",
    "edf-budget-planner": "production-app",
    "crash-dash": "production-app",
}


def git(repo: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(repo), *args], check=True, capture_output=True, text=True
    ).stdout.strip()


def scan(projects: Path) -> list[dict]:
    rows = []
    for d in sorted(projects.iterdir()):
        name = d.name
        if name in EXCLUDE or name.endswith("-wt") or not (d / ".git").is_dir():
            continue
        dates = git(d, "log", "--reverse", "--format=%as").splitlines()
        if not dates:
            continue
        rows.append(
            {
                "repo": name,
                "first_commit": dates[0],
                "last_commit": dates[-1],
                "commits": int(git(d, "rev-list", "--count", "HEAD")),
                "stage": STAGE.get(name, "unassigned"),
            }
        )
    rows.sort(key=lambda r: (r["first_commit"], r["repo"]))
    return rows


def chapter_file(number: int, repo: str) -> Path:
    return JOURNEY / f"{number:02d}-{repo}.md"


def stub(number: int, r: dict) -> str:
    return (
        "---\n"
        f"title: {r['repo']}\n"
        f"repo: {r['repo']}\n"
        f"start: {r['first_commit']}\n"
        f"end: {r['last_commit']}\n"
        f"commits: {r['commits']}\n"
        f"stage: {r['stage']}\n"
        "tools: []\n"
        "deck: false\n"
        "artifact: pending\n"
        "---\n\n"
        f"# {number:02d} · {r['repo']}\n\n"
        "## What I was trying to do\n\n"
        "## What didn't work\n\n"
        "## What I learned\n\n"
        "## Artifact\n"
    )


def experiments(rows: list[dict]) -> str:
    lines = [
        "# 00 · Experiments\n",
        f"Repos with fewer than {MIN_COMMITS} commits: one line each, no chapter.\n",
    ]
    for r in rows:
        lines.append(
            f"- **{r['repo']}** · {r['first_commit']} · {r['commits']} commits · outcome: pending"
        )
    return "\n".join(lines) + "\n"


def index(chapters: list[tuple[int, dict]], small: list[dict]) -> str:
    out = [
        "# Journey index\n",
        "Generated by `scripts/timeline-from-git.py` from `content/timeline.json`. Do not hand-edit.\n",
        "| # | repo | start | end | commits | stage | chapter |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for n, r in chapters:
        f = chapter_file(n, r["repo"]).name
        out.append(
            f"| {n:02d} | {r['repo']} | {r['first_commit']} | {r['last_commit']} | "
            f"{r['commits']} | {r['stage']} | [{f}]({f}) |"
        )
    for r in small:
        out.append(
            f"| 00 | {r['repo']} | {r['first_commit']} | {r['last_commit']} | "
            f"{r['commits']} | {r['stage']} | [00-experiments.md](00-experiments.md) |"
        )
    return "\n".join(out) + "\n"


def main() -> int:
    projects = Path(sys.argv[1] if len(sys.argv) > 1 else "~/projects").expanduser()
    rows = scan(projects)
    JOURNEY.mkdir(parents=True, exist_ok=True)
    TIMELINE.write_text(json.dumps(rows, indent=2) + "\n")

    big = [r for r in rows if r["commits"] >= MIN_COMMITS]
    small = [r for r in rows if r["commits"] < MIN_COMMITS]
    chapters = list(enumerate(big, start=1))

    created = []
    for n, r in chapters:
        p = chapter_file(n, r["repo"])
        if not p.exists():
            p.write_text(stub(n, r))
            created.append(p.name)
    if small and not EXPERIMENTS.exists():
        EXPERIMENTS.write_text(experiments(small))
        created.append(EXPERIMENTS.name)
    INDEX.write_text(index(chapters, small))

    print(
        f"{len(rows)} repos → {TIMELINE.relative_to(ROOT)}, {INDEX.relative_to(ROOT)}"
    )
    if created:
        print("created: " + ", ".join(created))
    return 0


if __name__ == "__main__":
    sys.exit(main())
